### ISSUE TITLE
Custom field name for policy effect

### ISSUE THREAD

**Issue by anhldbk** [casbin/jcasbin#102]
Hi there,

I see an error while customizing policy model

```
# Here I use `effect` instead of `eft`
[policy_definition]
p = subject, object, act, effect
```

Here what the error looks like:

![Screen Shot 2020-10-09 at 18 20 36](https://user-images.githubusercontent.com/3270746/95577330-280ad680-0a5c-11eb-9a01-92b8e9c5b7bf.png)

If I modify `effect` back to `eft`, everything works normally.

Would you please tell me is this an intended behaviour?

Thank you.

**Comment by hsluoyz** [comment]
@anhldbk hi, you are sending to the wrong place. Please send online editor related questions to: https://github.com/casbin/casbin-editor

**Comment by anhldbk** [comment]
@hsluoyz Diving into jcasbin code base, I've found [following logic](https://github.com/casbin/jcasbin/blob/master/src/main/java/org/casbin/jcasbin/effect/DefaultEffector.java#L31-L76)

```java
    public boolean mergeEffects(String expr, Effect[] effects, float[] results) {
        boolean result;
        if (expr.equals("some(where (p_eft == allow))")) {
            result = false;
            for (Effect eft : effects) {
                if (eft == Effect.Allow) {
                    result = true;
                    break;
                }
            }
        }
        //
    }
```

Looks like it's hard coded into the implementation.
