### ISSUE TITLE
Create a jCasbin authorization module for Play

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#104]
See: http://playframework.org/

The repo is created here: https://github.com/jcasbin/play-authz , you can make PR to add code to it.

You can see existing similar authorization modules for Play as reference: https://www.playframework.com/documentation/2.8.x/ModuleDirectory#Authentication-(Login-&-Registration)-and-Authorization-(Restricted-Access)
 
![image](https://user-images.githubusercontent.com/3787410/158736086-9afed203-0145-45bd-a9c7-938ec9c5e0a9.png)

You can refer to how we make middleware for other web frameworks like:

- SpringBoot: https://github.com/jcasbin/casbin-spring-boot-starter
- Shiro: https://github.com/jcasbin/shiro-casbin
- JFinal: https://github.com/jcasbin/jfinal-authz

**Comment by hsluoyz** [comment]
@sanbit876 see my updated comments

**Comment by sanbit876** [comment]
Hey @hsluoyz thank u for the updated comment, I have gone through the Documentation of the Play-Framework and integration of the other web frameworks with casbin. Can u guide me on creation of the required classes and methods for the middleware as i saw that each middleware were implemented using different methods and were complex.

**Comment by hsluoyz** [comment]
@sanbit876 see my updated comments

**Comment by dspasojevic** [comment]
@sanbit876 did you end up starting on this? I am slightly interested in implementing it.

**Comment by hsluoyz** [comment]
@dspasojevic I don't think so. You are welcome to contribute it!

**Comment by FoeverA0** [comment]
[WeOpen Star]I would like to help

**Comment by hsluoyz** [comment]
Done at: https://github.com/jcasbin/play-authz
