### ISSUE TITLE
Add the FilteredAdapter interface

### ISSUE THREAD

**Issue by fangzhengjin** [casbin/jcasbin#107]
For Golang Casbin, we designed an interface for FilteredAdapter: https://github.com/casbin/casbin/blob/master/persist/adapter_filtered.go

For Java, we only have a FilteredAdapter class which is actually an implementation of the FilteredAdapter interface for files: https://github.com/casbin/jcasbin/blob/a69db939567061ac25f415bb722d1cbd76effb44/src/main/java/org/casbin/jcasbin/persist/file_adapter/FilteredAdapter.java

Now, we need to first extract out the interface for FilteredAdapter in Java like how we did in Golang.

This issue is for another issue: https://github.com/jcasbin/casbin-spring-boot-starter/issues/16

**Comment by hsluoyz** [comment]
@RuiyuShan can you take it?
