### ISSUE TITLE
Add features like Dispatcher, UpdatableAdapter and DistributedEnforcer

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#117]
Someone has already implemented the code in PR: https://github.com/casbin/jcasbin/pull/111

But I want to re-arrange and split that PR into multiple smaller PRs for easy reviewing, like:

- [x] Dispatcher is a PR: fixed by: https://github.com/casbin/jcasbin/pull/118
- [x] UpdatableAdapter is a PR: fixed by: https://github.com/casbin/jcasbin/pull/120
- [ ] DistributedEnforcer is a PR

I hope someone can extract the code from it, improve the code if anything is wrong and make multiple smaller PRs.

**Comment by hsluoyz** [comment]
Done by 3 PRs, kudos to @shy1st !

**Comment by shy1st** [comment]
> Done by 3 PRs, kudos to @shy1st !

I'm glad to get your praise,Thank you!
