### ISSUE TITLE
Save model in Databse

### ISSUE THREAD

**Issue by M-Razavi** [casbin/jcasbin#12]
Is it possible to save whole model in databse. (Currently the Adaptor implementations (File & JDBC) only save g,p section of model into database.)

**Comment by hsluoyz** [comment]
The model can be loaded from file, API or a static string: https://casbin.org/docs/en/model-storage , we didn't provide a storing to DB mechanism like adapter for model. But it's always easy to store it by yourself as a single string.

If the model is not often changed and you don't want to have files, my advice is to store it as a Java string in the source code.

**Comment by M-Razavi** [comment]
The relation between Roles and their Permission sometimes change so the matcher section of the model should be changed. 
Saving in a simple string is not a proper way for complicated matcher like below and I prefer to have a better structure for that.

`m = (r.act == "view" &&  isIn(r.obj.branchId, r.sub.branchIds)) || (hasRole("manager",r.sub.roles) && r.act == "view") ||  isValidTimeForUser(r.sub) ||  (hasRole("manager",r.sub.roles) && (r.act == "confirm" || r.act == "reject")) || (hasRole("operator",r.sub.roles) && (r.act == "create" || r.act == "edit")) || (hasRole("reviewer",r.sub.roles) && r.obj.state== "APPROVED" && (r.act == "view"))`

**Comment by hsluoyz** [comment]
Then you should use the API way: https://casbin.org/docs/en/model-storage#load-model-from-code

```go
// Initialize the model from Go code.
m := casbin.NewModel()
m.AddDef("r", "r", "sub, obj, act")
m.AddDef("p", "p", "sub, obj, act")
m.AddDef("g", "g", "_, _")
m.AddDef("e", "e", "some(where (p.eft == allow))")
m.AddDef("m", "m", "g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act")

// Load the policy rules from the .CSV file adapter.
// Replace it with your adapter to avoid files.
a := persist.NewFileAdapter("examples/rbac_policy.csv")

// Create the enforcer.
e := casbin.NewEnforcer(m, a)
```

But you still can only use matcher as a whole string via Casbin's API. You may need to write custom code to operate on the matcher string before feeding it to Casbin.
