### ISSUE TITLE
Add globMatch pattern

### ISSUE THREAD

**Issue by nodece** [casbin/jcasbin#121]
The [`glob`](https://en.wikipedia.org/wiki/Glob_(programming)) pattern is most welcome, we need to add a name called `globMatch` to the model to call this pattern. 

Can anyone add the `globMatch` to jCasbin?

**Comment by hsluoyz** [comment]
I think we can add this.

**Comment by shy1st** [comment]
@nodece Excuse me，May I ask you a question? Do you mean that when we use the globMatch，we will get some file path，then we traverse these file paths and import their contents to the model?

**Comment by hsluoyz** [comment]
@shy1st you can copy the implementation of Golang Casbin: https://github.com/casbin/casbin/pull/397

**Comment by shy1st** [comment]
@hsluoyz Thanks, I will fix this issue.
