### ISSUE TITLE
could enforcer support a List or Array

### ISSUE THREAD

**Issue by namedHK** [casbin/jcasbin#14]
now enforcer only can put object...,Can it be parsed into an array than put in enforcer

**Comment by hsluoyz** [comment]
@namedHK ,

jCasbin uses [aviator](https://github.com/killme2008/aviator) as the matcher's expression parser. So all supported Aviator elements will also be available in jCasbin. AFAIK, Aviator supports to have array or list in the expression. But what operation will you need? get element (a[10]) or tell if an element is in the array? (if v in a)?

Here's Aviator's documentation: https://github.com/killme2008/aviator/wiki#%E5%BC%BA%E5%A4%A7%E7%9A%84-seq-%E5%BA%93. But I don't know if you can understand Chinese..

**Comment by hsluoyz** [comment]
Closed as stale.
