### ISSUE TITLE
Rename all "jcasbin"s to "casbin" except this GitHub repo name

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#143]
We will rename to "casbin" for everywhere including the Maven package manager, except this GitHub repo name to differentiate with Go's Casbin.

**Comment by shy1st** [comment]
The following project does not use "casbin" for groupId config.

1. vertx-casbin
2. jfinal-authz
3. jcasbin-nutz-plugin
4.jcasbin-springboot-plugin
5.jfinal-demo

**Comment by Zxilly** [comment]
Reserve current version jCasbin, and make further update in the Casbin may be a good idea.

**Comment by hsluoyz** [comment]
@Zxilly what do you mean?

**Comment by Zxilly** [comment]
@hsluoyz Keep this version of `jCasbin` for compatibility with other module, but no longer develop on this.
But create a new repository named `casbin` ,and make further contribution on that.

**Comment by hsluoyz** [comment]
@Zxilly the github repo doesn't matter. The commits remain anyway. I'm talking abou the Maven central. We will freeze the new versions under jcasbin and release new versions with casbin.

**Comment by hsluoyz** [comment]
@shy1st I don't know how Maven Central treats such a situation. Is Casbin a new package than jCasbin?  If yes, then we are releasing new package.

**Comment by Zxilly** [comment]
> @Zxilly the github repo doesn't matter. The commits remain anyway. I'm talking abou the Maven central. We will freeze the new versions under jcasbin and release new versions with casbin.

Yes, that's what I mean. There will 2 packages exist at same time

**Comment by shy1st** [comment]
Yes, that's what I mean. There will be 2 packages exist at same time

**Comment by hsluoyz** [comment]
@shy1st In the Java side (code, etc.), there should be only "casbin", there's no "jcasbin". "jcasbin" is only used in this repo name and also in Casbin official website.

**Comment by shy1st** [comment]
@hsluoyz I think this is mainly reflected in the setting of groupid in POM files. In some projects, the groupid is set as org.jcasbin(eg:vertx-casbin), which is incorrect. This will cause an exception when published to the central repository(In fact, vertx-casbin has not published to the central repository）.

**Comment by hsluoyz** [comment]
@shy1st good, then fix those wrong group IDs.

**Comment by Kininaru** [comment]
trying to work on this

**Comment by hsluoyz** [comment]
@shy1st , let me introduce @Kininaru , @Kininaru is our technical writer for Casbin docs & website. He also has some interest in languages like C++, Java, etc., so he will hang around our repos. Hope @Kininaru can be a help for you!

**Comment by shy1st** [comment]
@Kininaru  Welcome!

**Comment by shy1st** [comment]
@Kininaru @hsluoyz I think all the project in jcasbin organization has renamed. Now we can close this issue.

**Comment by hsluoyz** [comment]
Great!
