### ISSUE TITLE
"ABAC with policy rule" doesn't work

### ISSUE THREAD

**Issue by uPagge** [casbin/jcasbin#145]
I have a policy like this, in the editor it works

![изображение](https://user-images.githubusercontent.com/40397740/108187945-10d1a900-7120-11eb-84df-8fe5a2fa418d.png)

But in java it refuses to work

![изображение](https://user-images.githubusercontent.com/40397740/108188272-732aa980-7120-11eb-9e43-e2e769b579dc.png)

![изображение](https://user-images.githubusercontent.com/40397740/108187825-f26bad80-711f-11eb-92e6-d38a5e814810.png)
![изображение](https://user-images.githubusercontent.com/40397740/108187854-f8fa2500-711f-11eb-9656-fcc6fba309ff.png)

![изображение](https://user-images.githubusercontent.com/40397740/108188210-5e4e1600-7120-11eb-8f41-110006e6267f.png)

What could be the problem?

**Comment by hsluoyz** [comment]
@shy1st please take a look.

**Comment by shy1st** [comment]
I think there is something wrong with the way you use it.You should create a class and then create a property named "name" in the class and ensure that the class has the "Name" attribute of the get method and to ensure that the access permissions of this class and this property are "public". Then calling the enforce method of Enforcer, the first parameter is an instantiated object of this class. Please look at the example I wrote:
![捕获](https://user-images.githubusercontent.com/34126552/108298481-feb34180-71d7-11eb-8736-6427a7fd1c3d.PNG)

**Comment by uPagge** [comment]
@shy1st I tried your example and everything turned out in a separate file. But as soon as I returned to Spring Boot it stopped working.

![изображение](https://user-images.githubusercontent.com/40397740/108315505-90b54d00-71cc-11eb-9793-f0f1f244a773.png)

**Comment by uPagge** [comment]
@shy1st I think I found what the problem is. The entity I'm using has lazy initialized fields. And apparently because of them this problem occurs. I created another entity with only one Name field in the Srpting Boot project I wrote about above and it worked. But it's very sad how to do without lazy fields.

**Comment by shy1st** [comment]
You can try to wake up this fields before using enforcer method.Maybe you can call one method of the field(try to use the field) to initial the field.Do you think it's alright? @uPagge

**Comment by shy1st** [comment]
@uPagge We use janino instead of beanShell to implement eval function of BuiltInFunctions in jcasbin v1.7..It's possible that your problem has solved.Please try again and let us know if you still have problems.

**Comment by hsluoyz** [comment]
@uPagge plz check if it's fixed in latest v1.7.1: https://github.com/casbin/jcasbin/releases/tag/v1.7.1

**Comment by hsluoyz** [comment]
Closed as resolved.
