### ISSUE TITLE
I propose to abandon BeanShell in the implementation of the eval function.

### ISSUE THREAD

**Issue by The28AWG** [casbin/jcasbin#146]
BeanShell does not perform well in a multithreaded environment.
I tried to stress test the eval function, I was wondering how it would behave under heavy load. For this I used the script https://github.com/rodrigorodrigues/quarkus-vs-springboot-reactive-rest-api/blob/master/naive-stress-test.sh
At some point, the interpreter starts to crash and many errors appear in the console:

	Caused by: java.lang.NullPointerException
	Sourced file: inline evaluation of: ``import com.the28awg.common.model.permission.Permission; return r.get("context"). . . . '' unknown error: null : at Line: 2 : in file: inline evaluation of: ``import com.the28awg.common.model.permission.Permission; return r.get("context"). . . . '' : return r .get ( "context" ) .has ( Permission .REQUEST ) ; 

	at bsh.Interpreter.eval(Interpreter.java:706)
	at bsh.Interpreter.eval(Interpreter.java:750)
	at bsh.Interpreter.eval(Interpreter.java:739)
	at org.casbin.jcasbin.util.BuiltInFunctions.eval(BuiltInFunctions.java:337)
	at org.casbin.jcasbin.util.function.EvalFunc.call(EvalFunc.java:34)
	at Script_1613938148563_0.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:72)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:399)
	at com.the28awg.common.enforcer.DefaultEnforcer.has(DefaultEnforcer.java:91)

It is not very clear how to treat such an error. So I wrote a replacement for the eval function using the Janino library http://janino-compiler.github.io/janino/
I will not attach the code, since I did not strive for something universal and wrote it for myself.
An obvious plus for me is that this library is trusted by the logback logger (ch.qos.logback.classic.boolex.JaninoEventEvaluator).
In addition, Janino is updated quite often, the last update was in January 2021, while BeanShell has not been updated for a very long time, and it is not known what state of development is now. In my opinion, everyone forgot about this project.

A bit off topic, but during testing it turned out that it is better to put the eval function at the end of the [matchers] section.

**Comment by shy1st** [comment]
Thank you for your suggestion, we will improve it.

**Comment by shy1st** [comment]
@The28AWG Sorry, I have some problems with janino.Suppose I want to execute the "r. get ("sub). age", when compiling this statement with expressionEvaluator, it will appear the error, which context is "java.lang.object" has no field "age".Exactly, 
the return type of "r.get("sub)" statement is "Object"，so it has no field "age" is reasonable.So it failed to compile.Maay I ask you what you think about it?

**Comment by The28AWG** [comment]
The problem arises from the fact that you modify the expression before sending it to the interpreter. Just change the expression to something else.
```java
public class EvalFunction extends AbstractFunction {
    private final Map<String, ScriptEvaluator> evaluator = new ConcurrentHashMap<>();

    public AviatorObject call(
            Map<String, Object> env,
            AviatorObject arg1
    ) {
        String ev = FunctionUtils.getStringValue(arg1, env);
        ScriptEvaluator scriptEvaluator = evaluator.computeIfAbsent(ev, s -> {
            try {
                return new ScriptEvaluator(
                        getDecoratedExpression(s),
                        boolean.class,
                        env.keySet()
                           .toArray(new String[0]),
                        env.values()
                           .stream()
                           .map(Object::getClass)
                           .toArray(Class[]::new)
                );
            } catch (CompileException e) {
                e.printStackTrace();
                return null;
            }
        });

        if (scriptEvaluator != null) {
            try {
                return AviatorBoolean.valueOf(
                        (Boolean) scriptEvaluator.evaluate(env.values().toArray())
                );
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }
        }
        return AviatorBoolean.valueOf(false);
    }

    protected String getDecoratedExpression(String expression) {
        // modify expression if need
        if (!expression.contains("return")) {
            expression = "return " + expression + ";";
        }
        return expression;
    }

    @Override
    public String getName() {
        return "eval";
    }
}
```

**Comment by The28AWG** [comment]
r.get ("sub").age does not exist. The expression is simply converted thanks to this code:
https://github.com/casbin/jcasbin/blob/d46d1a0bb63c984b3aa898732fc5045c005522de/src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java#L389-L393

**Comment by shy1st** [comment]
> r.get ("sub").age does not exist. The expression is simply converted thanks to this code:
> https://github.com/casbin/jcasbin/blob/d46d1a0bb63c984b3aa898732fc5045c005522de/src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java#L389-L393

![QQ图片20210224223444](https://user-images.githubusercontent.com/34126552/109015843-84f7e800-76f0-11eb-89ca-f424a631b644.png)
@The28AWG Here is my code, you can see I used this code.

**Comment by The28AWG** [comment]
Map<String, Object> env contains r_* fields and p_* name fields.
you need replace code:
```java
eval = eval.replace("." + s, ".get(\"" + s + "\")");
```
to:
```java
eval = eval.replace("." + s, "_" + s + "");
```
And initialize parameterNameList, parameterValueList and parameterClassList:
```java
        List<String> parameterNameList = new ArrayList<>();
        List<Object> parameterValueList = new ArrayList<>();
        List<Class<?>> parameterClassList = new ArrayList<>();
        for (Map.Entry<String, Object> entry: env.entrySet()) {
            parameterNameList.add(entry.getKey());
            parameterValueList.add(entry.getValue());
            parameterClassList.add(entry.getValue().getClass());
        }
        evaluator.setParameters(parameterNameList.toArray(new String[0]), parameterClassList.toArray(new Class[0]));
```

**Comment by The28AWG** [comment]
This is due to the stricter set of code in janino. See http://janino-compiler.github.io/janino/ : 

> Limitations
> ....
> Java 5 language features:
> Type arguments: Are parsed, but otherwise ignored. The most significant restriction that follows is that you must cast return values from method invocations, e.g. "(String) myMap.get(key)"

**Comment by shy1st** [comment]
@The28AWG Thank you very much for your advice!
