### ISSUE TITLE
What is the status of polyglot casbin projects?

### ISSUE THREAD

**Issue by dgrnbrg** [casbin/jcasbin#152]
Hello, I've read through the documentation on casbin.org, but I can't find concrete information about polyglot projects. Are the postgres database formats compatible between Python, Java, and Go?

Can I use Casdoor or another Admin Portal from casbin.org as a mechanism to configure permissions?

My group develops primarily on the JVM, but we use Python and Rust at times. It looks like Casbin would be a great solution to integrate RBAC throughout our applications, but I'm struggling to find any references to Casbin customers using multiple interfaces at once.

Thank you!

**Comment by hsluoyz** [comment]
Hi @dgrnbrg 

> Hello, I've read through the documentation on casbin.org, but I can't find concrete information about polyglot projects. Are the postgres database formats compatible between Python, Java, and Go?

Yes, all Casbin adapters should follow the same data format, including default table name, column names. If you find any adapter doesn't follow the same behavior, please tell us and we will fix it.

> Can I use Casdoor or another Admin Portal from casbin.org as a mechanism to configure permissions?

Yes. Casdoor is the current recommendation for permision management.

If you have any other issues, please tell us, thanks!

**Comment by hsluoyz** [comment]
Closed as resolved.
