### ISSUE TITLE
Question: Is there a way to escape comma in policy rule?

### ISSUE THREAD

**Issue by young-zy** [casbin/jcasbin#158]
Hi,

I noticed that jcasbin is using [aviator](https://github.com/killme2008/aviator) as its evaluator, 
and I'm trying to use some of its builtin functions ( to be specific, function "include" ) which takes in more than one parameter (so there will be comma in expression).

If the expression is written in matcher, everything works fine.
But if It is written in policy rule, the parser is unhappy and throws an exception

https://github.com/casbin/jcasbin/blob/4227edc637aace211983976032c0cec824afe67e/src/main/java/org/casbin/jcasbin/util/Util.java#L201-L214

The code above seems to split the line directly by comma, which breaks the expression.

So I'd like to question if there is any plan on the support of escaping comma?

P.S. I've also tried to use SQL adapter, but with no luck. It seems that lines being read from database still gets concated and goes into this function

**Comment by hsluoyz** [comment]
@shy1st

**Comment by arti0798** [comment]
I m on it.

**Comment by arti0798** [comment]
I had tried to run this but its shows error 'ERROR 21647 --- [enerContainer-1] o.s.d.r.l.RedisMessageListenerContainer : Connection failure occurred. Restarting subscription task after 5000 ms'

**Comment by arti0798** [comment]
will you please help me on this?

**Comment by shy1st** [comment]
@arti0798 It may be caused by the failure of redis connection.Can you tell me why you use redis?The pom.xml of jcasbin has no dependency about redis.

**Comment by arti0798** [comment]
I haven't use redis..it is already there and there is no pom file....actually there is application.yml file

**Comment by shy1st** [comment]
@arti0798 I guess you're using casbin-spring-boot-starter, please replace the redis configuration with your own.about caspin spring boot starter.

**Comment by arti0798** [comment]
okay, I will try.

**Comment by shink** [comment]
> okay, I will try.

Hello, can I help you? I will try my best.

**Comment by fangzhengjin** [comment]
> @arti0798 I guess you're using casbin-spring-boot-starter, please replace the redis configuration with your own.about caspin spring boot starter.

I think this is nothing relationship with Casbin-Spring-Boot-Starter. In Casbin-Spring-Boot-Starter, you need to actively introduce Redis dependencies and enable REDIS-WATCH configuration. If you do not explicitly enable Redis-Watch, it will not be automatically Enable Redis-Watch.
Please check if you introduce Redis dependencies and configure the Redis connection correctly.

**Comment by hsluoyz** [comment]
@arti0798 please open a new issue for your Redis problem. This issue is only for resolving the issue for @young-zy

**Comment by hsluoyz** [comment]
@shy1st plz focus on and help resolve the initial issue: `Question: Is there a way to escape comma in policy rule?`

**Comment by shy1st** [comment]
@hsluoyz As we talked before, if we use / to escape a comma, we need to distinguish whether the current adapter is a fileadapter. If it is a fileadapter, we can use / to escape a comma. But we can't get adapter information in other functions which use the splitCommunadelimited function.For example:
````java
public static void loadPolicyLine(String line, Model model) {
        if (line.equals("")) {
            return;
        }

        if (line.charAt(0) == '#') {
            return;
        }

        String[] tokens = splitCommaDelimited(line);

        String key = tokens[0];
        String sec = key.substring(0, 1);
        model.model.get(sec).get(key).policy.add(Arrays.asList(Arrays.copyOfRange(tokens, 1, tokens.length)));
    }
````

I have another idea. we can change like this:
````java
public static String[] splitCommaDelimited(String s) {
        if (s == null) {
            return null;
        }
        return s.trim().split("\\s*,\\s+");
    }
````
In this way, you need to make sure that there is a space after the comma in the model file and the policy file, so that they can be split.
(ps: In the casbin of go, it use the string.split() directly and can also iidentify blank space.)

**Comment by hsluoyz** [comment]
@shy1st we can add a new function called `loadPolicyLineForFile()`, this function will do the job and the built-in file adapter will use this one.

**Comment by arti0798** [comment]
@fangzhengjin I had already tried dependencies but that's not working.

This is what I had tried - 
  1.  //implementation 'org.casbin:casbin-spring-boot-starter:version'
  2.  // implementation 'org.springframework.boot:spring-boot-starter-data-redis:2.2.0.RELEASE'
  3.  // implementation 'redis.clients:jedis:2.8.0'
   4.  // implementation group: org.springframework.boot 
        // name: spring-boot-starter-data-redis 
        // version: 2.4.0-M3
these four I had tried.

**Comment by arti0798** [comment]
@shink  Thanks!  I had already mention the problem.

**Comment by young-zy** [comment]
@fangzhengjin @shy1st

**Comment by shy1st** [comment]
> @fangzhengjin @shy1st
> How about using the rules that csv uses: escaping by adding quotes("").
> Also, since some of the adapters may have their own separation rules( for example, SQL columns ), I think exposing an interface that takes in an array might be a better practice.

Do you mean to add "" to a word to escape comma, such as "Alice, Bob"?
As for the array, we can import policy through list.

**Comment by young-zy** [comment]
@shy1st 
Yep

Also: 
> [RFC-4180](https://tools.ietf.org/html/rfc4180)    
> 7.  If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote.  For example:
>      ` "aaa","b""bb","ccc"`

**Comment by arti0798** [comment]
@shy1st 
or we can do this s.split(", (?=\\w+=)")
Which says split on each ", " which is followed by some word-characters and an =

**Comment by shy1st** [comment]
> @shy1st
> or we can do this s.split(", (?=\w+=)")
> Which says split on each ", " which is followed by some word-characters and an =

Did you have a try？I had a try and it can not pass the test

**Comment by arti0798** [comment]
@shy1st  I m still having that Redis problem...that's why I havn't try but that might work.

**Comment by arti0798** [comment]
> @fangzhengjin I had already tried dependencies but that's not working.
> 
> This is what I had tried -
> 
> 1. //implementation 'org.casbin:casbin-spring-boot-starter:version'
> 2. // implementation 'org.springframework.boot:spring-boot-starter-data-redis:2.2.0.RELEASE'
> 3. // implementation 'redis.clients:jedis:2.8.0'
> 4. // implementation group: org.springframework.boot
>    // name: spring-boot-starter-data-redis
>    // version: 2.4.0-M3
>    these four I had tried.

please someone help me on this.

**Comment by fangzhengjin** [comment]
Can you provide a code repository that can be reproduced?



---Original---
From: "Arti ***@***.***&gt;
Date: Fri, Apr 2, 2021 17:31 PM
To: ***@***.***&gt;;
Cc: "ZhengJin ***@***.******@***.***&gt;;
Subject: Re: [casbin/jcasbin] Question: Is there a way to escape comma in policy rule? (#158)




  
@fangzhengjin I had already tried dependencies but that's not working.
 
This is what I had tried -
  
//implementation 'org.casbin:casbin-spring-boot-starter:version' 

// implementation 'org.springframework.boot:spring-boot-starter-data-redis:2.2.0.RELEASE' 

// implementation 'redis.clients:jedis:2.8.0' 

// implementation group: org.springframework.boot
 // name: spring-boot-starter-data-redis
 // version: 2.4.0-M3
 these four I had tried. 
  
please someone help me on this.

**Comment by hsluoyz** [comment]
@arti0798 hi, please stop talking about Redis issue in this thread, use a new issue for your topic. Thanks!

**Comment by hsluoyz** [comment]
> @fangzhengjin @shy1st
> How about using the rules that csv uses: escaping by adding quotes("").
> Also, since some of the adapters may have their own separation rules( for example, SQL columns ), I think exposing an interface that takes in an array might be a better practice.

Your words inspired me. @shy1st is there any popular CSV parsing library for Java? We should use such a library instead of using our own home-made parsing code. Using such a lib will offer all the CSV escaping schemes.

**Comment by shy1st** [comment]
@hsluoyz  I think this idea is good. I wrote an implementation for this idea
