### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by divyagar** [casbin/jcasbin#165]
While running basic permission checking code provided in tutorial:
```java
Enforcer e = new Enforcer("basic_model.conf", "basic_policy.csv");
String sub = "alice"; // the user that wants to access a resource.
String obj = "data1"; // the resource that is going to be accessed.
String act = "read"; // the operation that the user performs on the resource.

if (e.enforce(sub, obj, act) == true) {
   // permit alice to read data1
   System.out.println("permit alice to read data1");
} else {
   // deny the request, show an error
   System.out.println("permission denied");
}
```
compiler is showing following error followed by result of above code:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
permit alice to read data1
```

**Comment by shy1st** [comment]
please add the following dependency.
`        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
            <scope>test</scope>
        </dependency>`

**Comment by hsluoyz** [comment]
@shy1st can we fix this warning for users don't use slf4j?

**Comment by divyagar** [comment]
@hsluoyz Can we add dependency of slf4 in installation section as a requirement to make user aware that this library is being used in jcasbin?
