### ISSUE TITLE
Can support dynamic matching?

### ISSUE THREAD

**Issue by mango-6bd** [casbin/jcasbin#169]
Can support dynamic matching?

**Comment by hsluoyz** [comment]
We should add the `EnforceWithMatcher()` API: https://casbin.org/docs/en/management-api#enforcewithmatcher

**Comment by hsluoyz** [comment]
@shy1st

**Comment by shy1st** [comment]
OK, I will complete this requirement in the next few days

**Comment by hsluoyz** [comment]
@shink

**Comment by shink** [comment]
> @shink

Ok, I will do it.

**Comment by hsluoyz** [comment]
@shink @shy1st any progress?

**Comment by shink** [comment]
> @shink @shy1st any progress?

I' m debugging.
BTW, should I use [this](https://github.com/casbin/casbin/blob/380ee0f0d17cf2eed3e97b2069e6a0ee9502d8ac/enforcer_test.go#L204) for testing?

**Comment by hsluoyz** [comment]
@mango-6bd can you state your requirement more specifically?

**Comment by shink** [comment]
> @mango-6bd can you state your requirement more specifically?

I think we should add an optional `matcher` parameter to the `enforce()` API and define serveral different matchers to test it.
I will finish it as soon as possible.

**Comment by hsluoyz** [comment]
@shink see how Goland implements it.

**Comment by shink** [comment]
@hsluoyz OK, I will. Casbin is implemented in the above way. BUT it doesn't seem to test the [enforceWithMatcher](https://github.com/casbin/casbin/blob/68bec4fd804ec3b25940bec067e088b236fe7284/enforcer.go#L637) function.

**Comment by hsluoyz** [comment]
Closed as stale.
