### ISSUE TITLE
How to implement WatcherEx when using an Adaptor

### ISSUE THREAD

**Issue by barnesm999** [casbin/jcasbin#172]
I am trying to understand the expectation for an implementation of WatcherEx.

My understanding so far is that if I create a WatcherEx implementation, Enforcer methods like `addPolicy` will invoke my WatcherEx with specific policy changed information instead of just the generic update. I will then emit a message containing that information so other instances of my application can receive that message and can use it to update their in memory Model of the policies.

I am stuck currently on the consuming end of this implementation. Assuming my consumer has received a message and knows for example that I need to add a policy, how can I add that policy. The standard Watcher operates under the assumption that I need to reload the entire policy from the Adaptor but with WatcherEx I would like to update only the change that is needed. 

I thought to just call the appropriate Enforcer method, i.e, `addPolicy`.

Some issues I have are:

- Since I am using a JDBC adaptor the policy would be written to the DB again, creating a duplicate entry
- Since I am using Watchers, my WatcherEx would be invoked again

I believe what I need to do is update only the Model in my Enforcer. However I am used SyncedEnforcer and there doesn't seem to be a lock safe way to make changes to the Model that won't invoke the adaptor or watcher. I also can't extend SyncedEnforcer and add method for modify the model because the READ_WRITE_LOCK is private so I can't use it in my class to safely lock the model before writing.

Could you please provide guidance on the expected path forward? Are there any Java reference implementation examples of the WatcherEx interface you could share?

Thank you for your help.

**Comment by hsluoyz** [comment]
@shy1st

**Comment by shy1st** [comment]
You can refer to the example of rediswatcher in casbin-spring-boot-starter.
https://github.com/jcasbin/casbin-spring-boot-starter/blob/master/src/main/java/org/casbin/watcher/RedisWatcher.java

**Comment by barnesm999** [comment]
@shy1st 

The `RedisWatcher` only implements `Watcher`, not `WatcherEx`. That implementation still causes a reload of the entire casbin rule data set when a message is received. 

What I am hoping to achieve is to implement `WatcherEx` interface which if I understand the casbin docs should help avoid entire reloads and instead be able to just update based on what changed. 

I have partially implemented this on my end with inspiration from the `RedisWatcher you linked. I serialize the policy information which changed and include it in the message sent to redis. But when my message listener receives that message I am not sure how I am expected to update the casbin in memory Model.

As an example, if I called `Enforcer.addPolicy(...)` on one instance, my WatcherEx can serialize an object into the redis message that allows me to know it was an "addPolicy", what the policy which was added was, etc. Now on my second instance I have received this message and I want to update this second instances in memory model with the added policy. 

The problem is, if I call `Enforcer.addPolicy(...)` again from this second instance, it will write to the Adaptor again and trigger another Watcher message. There doesn't seem to be any exposed methods which will allow me to update only the model. I've considered doing `enforcer.getModel().addPolicy(...)` but this is not safe in a multi-threaded environment since I am not integrating with the write lock in your `SyncedEnforcer`. 

I want to make sure I am not missing something. To me it doesn't seem like there is any way to achieve this in the current code base but since the `WatcherEx` interface is present I would expect there to be some known path to implement. The best I have come up with is copying your entire `SyncedEnforcer` so I can add my own methods which will update the model and share the READ_WRITE_LOCK.

Thanks for your time.

**Comment by hsluoyz** [comment]
@barnesm999 I know what you mean. You want to know how to change other Casbin instances without triggering another watcher message. Actually that part is still not decided, as our WatchEx example code doesn't contain that: https://github.com/casbin/casbin/blob/2d182bff5bee483918ccb8316e564102dee7e794/watcher_ex_test.go#L27-L40

But we already start building the official Redis watcher (WatchEx) in both Go and Java:

- https://github.com/casbin/redis-watcher
- https://github.com/jcasbin/redis-watcher

Finally we will get a solution for this. We will close the issue here and plz watch the above two repos for progress.
