### ISSUE TITLE
Using priority-model Won't get any implicit permission

### ISSUE THREAD

**Issue by shink** [casbin/jcasbin#177]
- issue: [[Bug]Using priority-model Won't get any implicit permission](https://github.com/casbin/casbin/issues/762)
- pr: [fix: priority using non 1st element](https://github.com/casbin/casbin/pull/766)

This problem also exists in jcasbin. Do we need to fix it? I am willing to do it.

**Comment by hsluoyz** [comment]
@shink no need for now. There are already a lot of Java issues now: https://github.com/orgs/casbin/projects/2#column-12165804 Please fix them first and then come back to this.

**Comment by shink** [comment]
> @shink no need for now. There are already a lot of Java issues now: https://github.com/orgs/casbin/projects/2#column-12165804 Please fix them first and then come back to this.

OK, I will.
