### ISSUE TITLE
Groups are not isolated

### ISSUE THREAD

**Issue by lanmarti** [casbin/jcasbin#186]
As mentioned in https://github.com/casbin/casbin/issues/783 jCasbin does not seem to isolate different group systems, grouping items in one group system will result in them being grouped in any group system. See the original issue for examples.

Discovered in 1.7.4, confirmed in 1.8.4

**Comment by shy1st** [comment]
Thanks a lot! Maybe solving this problem will also solve these problems: #185 #https://github.com/casbin/jcasbin/issues/174

**Comment by hsluoyz** [comment]
@shy1st see: https://github.com/casbin/casbin/issues/783#issuecomment-832617046

**Comment by shink** [comment]
I'm on it.

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@hsluoyz @shy1st @lanmarti 
After my test on the cases in [casbin/casbin#783](https://github.com/casbin/casbin/issues/783),I found that all met expectations.
Has this bug been solved?Please let me know if there is anything missing

**Comment by hsluoyz** [comment]
May be already fixed by: https://github.com/casbin/jcasbin/pull/199 ?

@lanmarti can you check the latest version v1.12.0 ? https://github.com/casbin/jcasbin/releases/tag/v1.12.0

**Comment by lanmarti** [comment]
Indeed, #199 seems to have fixed it, and group isolation works from `v1.10.1` onwards. Thanks!
