### ISSUE TITLE
Add batchEnforce() API for jCasbin

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#187]
Required in: https://github.com/casbin/jcasbin/issues/185#issuecomment-831947838 by @imochurad 

See how Golang implemented it: https://github.com/casbin/casbin/search?q=batchEnforce&type=issues , Java can use a similar way.

**Comment by imochurad** [comment]
I would like to know a rough idea of when to expect this feature. Time is of the essence for me. And I will be either rolling out my own authorization framework or adopting jcasbin if this feature is complete and bug-free.

**Comment by hsluoyz** [comment]
@shy1st @shink can you implement this feature ASAP?

**Comment by hsluoyz** [comment]
@imochurad added: https://github.com/casbin/jcasbin/pull/188
