### ISSUE TITLE
[feature request] 需要添加针对MySQL的Policy持久化的适配器扩展

### ISSUE THREAD

**Issue by SollyTaylor** [casbin/jcasbin#2]
目前项目需求想直接使用casbin做权限策略管理，但是文件配置目前还不能完全适应具体到某个数据级别的权限控制，因而期望添加权限控制模块

**Comment by hsluoyz** [comment]
已经添加JDBC Adapter支持：https://github.com/jcasbin/jdbc-adapter，欢迎测试
