### ISSUE TITLE
jcasbin setUpdateCallback  callback  should be like golang version 

### ISSUE THREAD

**Issue by rongfengliang** [casbin/jcasbin#201]
current 
jcasbin watcher setUpdateCallback callback with `Runnable interface`

```code
void setUpdateCallback(Runnable runnable);
```
golang:

```code
SetUpdateCallback(func(string)) error
```
maybe better like golang  support pass one arg (if we want   control how to deal with policy reload with  some special content )

**Comment by shink** [comment]
@rongfengliang Very Cool!

But I think you can create a class which implements `Runable` interface and has a constructor with one parameter.

```java
class Func implements Runnable {

    private final String data;

    Func(String data) {
        this.data = data;
    }

    @Override
    public void run() {
        // do something ...
    }

}
```

Then you can call `setUpdateCallback()` like this.

```java
setUpdateCallback(new Func("data"));
```

Looking forward to your suggestions.

**Comment by rongfengliang** [comment]
@shink  yes.that's one way . keep method same  maybe better

**Comment by hsluoyz** [comment]
@shink can we provide a new overload function like `SetUpdateCallback(func(string)) error`?

**Comment by shink** [comment]
@hsluoyz Sure, if necessary. I will do it right away.

**Comment by hsluoyz** [comment]
@shink plz update our watchers (https://github.com/jcasbin?q=watcher&type=&language=&sort=) to support the new interface.
