### ISSUE TITLE
Special Grammar not supported

### ISSUE THREAD

**Issue by rob-spoor** [casbin/jcasbin#208]
The [Special Grammar](https://casbin.org/docs/en/syntax-for-models#special-grammer) is not supported. If I try the simple example matcher (`m = r.sub.Name in (r.obj.Admins)`), I get an error:

```
com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: unexpect token 'in', maybe forget to insert ';' to complete last expression  at 13, lineNumber: 1, token : [type='variable',lexeme='in'],
while parsing expression: `
r_sub.Name in^^^
`
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1494)
	at com.googlecode.aviator.AviatorEvaluatorInstance.access$000(AviatorEvaluatorInstance.java:180)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:1465)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:1462)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1449)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1413)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1400)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:439)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:546)
        ...
```

The parsing seems to incorrectly see `in` as variable and not as operator.

**Comment by hsluoyz** [comment]
@tangyang9464 

/cc @fangzhengjin

**Comment by tangyang9464** [comment]
@rob-spoor 
jcasbin can't support ``in``.In fact,just some languages can support this feature. 
see [feature-set-for-different-languages](https://casbin.org/docs/en/overview#feature-set-for-different-languages),the last point

**Comment by hsluoyz** [comment]
@tangyang9464 can we support `in` in Java? See: https://casbin.org/docs/en/syntax-for-models#expression-evaluator . Java uses: https://github.com/killme2008/aviatorscript as the expression evaluator. And `aviatorscript` is evolving faster now. We should send issue to their community for `in` support.

**Comment by rob-spoor** [comment]
@tangyang9464 I hadn't found this page yet. It only confirms my findings.

@hsluoyz it would be great if support for `in` could be added (through changes in `aviatorscript`). For now I guess I'll have to create a workaround.

**Comment by tangyang9464** [comment]
@hsluoyz 
see: [#379](https://github.com/killme2008/aviatorscript/issues/397)
AviatorScript can only use custom functions instead of native operator syntax, which means we need to analyze the syntax ``in`` by jCasbin.It seems difficult, and the implementation is different from other languages

**Comment by rob-spoor** [comment]
For now I've added a custom function that translates to `collection.contains(value)`. It has some drawbacks but at least this issue is not blocking anymore.

Having to implement this completely in jCasbin without support from AviatorScript seems quite hard, so I can understand if this issue won't get resolved anytime soon.

**Comment by hsluoyz** [comment]
@rob-spoor @tangyang9464 how about add a translation layer to translate the matcher from:

```
sub.Name in (obj.Admins)
```

to:

```
seq.some(obj.Admins, fn(x) { x.Name == sub.Name})
```

It's just a regex replacement I think.

**Comment by rob-spoor** [comment]
That could probably work, but it needs proper testing. Fortunately, the pattern seems to be quote simple: <value> in (<collection>). The value could be a string though.

**Comment by tangyang9464** [comment]
> That could probably work, but it needs proper testing. Fortunately, the pattern seems to be quote simple: in (). The value could be a string though.

For ```A in B```,we need to analyze what are A and B, but there is no precise separator,regex replacement is difficult.
Unless change the ``in`` syntax like ``regexMatch,keyGet2`` function

**Comment by hsluoyz** [comment]
Any update?
