### ISSUE TITLE
CustomFunction.replaceTargets replaces too much

### ISSUE THREAD

**Issue by rob-spoor** [casbin/jcasbin#209]
The way that `replaceTargets` works, it will replace more than one occurrence of dots if one request argument is an object that contains a property with the same name as another request argument. For example, if I have one request argument `sub` that is an object with property `value`, and another request argument `value`, then any occurrence of `r.sub.value` will not lead to `r_sub.value` but instead `r_sub_value`. As a result, no value can be found and evaluation fails.

As a workaround I can rename the `value` request argument, but it would be more readable to use proper names (`value` is just an example here).

**Comment by hsluoyz** [comment]
@tangyang9464 

/cc @fangzhengjin

**Comment by rob-spoor** [comment]
Perhaps an idea is to use a `Pattern` to find all strings that may need replacing, then replace only the first part in those.
A quick and dirty (case insensitive) regex that needs tweaking: `([a-z0-9]+)\.([a-z0-9]+)((?:\.[a-z0-9]+)*)`. This would yield 2 groups:
1. The part before the first dot.
2. The part after the first dot but before any second dot.
3. The part after any second dot.

If `<group1>_<group2>` is in `env`, then you could return `<group1>_<group2><group3>` (with group 3 replaced by the empty string if not present). Using matcher replacement `$1_$2$3` would also work.
