### ISSUE TITLE
Group with domain model not working

### ISSUE THREAD

**Issue by doctormacky** [casbin/jcasbin#232]
Hi guys, with the latest code chage. you guys change the unit test case directly as following:

**Model**:
```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _,_
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub) || g2(r.sub, p.sub, r.dom)) && r.obj == p.obj && r.act == p.act
```

Test case expression:

```csv
p, admin, domain1, data1, read
g, alice, group1
g2, group1, admin, domain1
```

T**est case**

```java
public void testGroupRoleManager() {
        Enforcer e = new Enforcer("examples/group_with_domain_model.conf", "examples/group_with_domain_policy.csv");
        testDomainEnforce(e, "alice", "domain1", "data1", "read", false);
    }
```
So, what alice can access ?

**Comment by doctormacky** [comment]
Please see this change here:
https://github.com/casbin/jcasbin/commit/4d91e84043eeb8d20eb5850e049928bde351a168

src/test/java/org/casbin/jcasbin/main/GroupRoleManagerTest.java

**Comment by hsluoyz** [comment]
@seriouszyx plz take a look

**Comment by seriouszyx** [comment]
Sorry for waiting. 
The unit test still uses the `DefaultRoleManager` and it will return false. You can use `GroupRoleManager` to make alice have the permission to read data1 as below.

```java
@Test
public void testGroupRoleManager() {
    Enforcer e = new Enforcer("examples/group_with_domain_model.conf", "examples/group_with_domain_policy.csv");
    GroupRoleManager groupRoleManager = new GroupRoleManager(10);
    e.setRoleManager("g", groupRoleManager);
    e.setRoleManager("g2", groupRoleManager);
    e.buildRoleLinks();
    testDomainEnforce(e, "alice", "domain1", "data1", "read", true);
}
```

I'm also confused why #199  changed the unit test case directly. And I have tried to get in touch with @shink and he will come to take a look sometime.

cc @hsluoyz

**Comment by hsluoyz** [comment]
@seriouszyx we should follow the Golang Casbin's behavior.

**Comment by seriouszyx** [comment]
@hsluoyz But I didn't find the `GroupRoleManager` in the [Golang Casbin](https://github.com/casbin/casbin/tree/master/rbac), instead in the [.NET Casbin](https://github.com/casbin/Casbin.NET/blob/master/NetCasbin/Rbac/GroupRoleManager.cs).

**Comment by hsluoyz** [comment]
@sagilio is our .NET maintainer, is the unit test change intended?

**Comment by doctormacky** [comment]
> Sorry for waiting. The unit test still uses the `DefaultRoleManager` and it will return false. You can use `GroupRoleManager` to make alice have the permission to read data1 as below.
> 
> ```java
> @Test
> public void testGroupRoleManager() {
>     Enforcer e = new Enforcer("examples/group_with_domain_model.conf", "examples/group_with_domain_policy.csv");
>     GroupRoleManager groupRoleManager = new GroupRoleManager(10);
>     e.setRoleManager("g", groupRoleManager);
>     e.setRoleManager("g2", groupRoleManager);
>     e.buildRoleLinks();
>     testDomainEnforce(e, "alice", "domain1", "data1", "read", true);
> }
> ```
> 
> I'm also confused why #199 changed the unit test case directly. And I have tried to get in touch with @shink and he will come to take a look sometime.
> 
> cc @hsluoyz

Good to kow, and verified.  Many thanks for this information, this means, we need to add following two lines after the fix
`    e.setRoleManager("g", groupRoleManager);
    e.setRoleManager("g2", groupRoleManager);`

**Comment by doctormacky** [comment]
suggest have more unit tests for each model including some negative, and positive test.

**Comment by doctormacky** [comment]
@seriouszyx @hsluoyz As @seriouszyx provided a workaround for the case, should I close this issue  or just leave it here until you add more unit case for `group with domain` model ?

**Comment by shink** [comment]
@hsluoyz @doctormacky @seriouszyx
Sorry for the late reply and my previous negligence. I'm willing to do some work to fix it.
But, should the enforcement result be `true` or `false`?
![1](https://user-images.githubusercontent.com/49934421/140704375-1660975f-79ae-4a1c-95fa-0a7304f7b4f4.png)

**Comment by doctormacky** [comment]
@hsluoyz I totally understand that we need to align with Golang Casbin.  However,  Group with Domain model is not an official model for Golang Casbin, and seems Golang edition will also support this feature. see(https://github.com/casbin/casbin/pull/874) 

So currently, Group with Domainn model is an extended model which only implemented by JCasbin.  there are some options for us:
1. add some official doc for JCasbin to announce that JCasbin support this model officially.
2. modify DefaultRoleManager, so that it can support it can support this model
3. drop this model and keep current status. but this will make JCasbin lose a very very important feature.

**Comment by sagilio** [comment]
`Group RoleManager` has been in the `Java/.NET` library for a long time (two or three years ago), and I keep this feature always ready.

**Comment by doctormacky** [comment]
I'd like to close this issue as the  the workaround are working https://github.com/casbin/jcasbin/issues/232#issuecomment-962399080

**Comment by hsluoyz** [comment]
@doctormacky can you review this PR? https://github.com/casbin/casbin/pull/874

**Comment by doctormacky** [comment]
> @doctormacky can you review this PR? [casbin/casbin#874](https://github.com/casbin/casbin/pull/874)

@hsluoyz  I'd like to do that, but I am not a go master, sorry about this case.
