### ISSUE TITLE
Can not escape comma in policy rule

### ISSUE THREAD

**Issue by huyphan-tiki** [casbin/jcasbin#243]
Hi,
I am using ABAC via "jcasbin" and I am facing an issue related to the CSV Parsing of the policy. I am using the 1.20.0 version. My policy includes double quotes and CSV Parser is failing with the following error:
```
java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
	at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:281)
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:158)
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:674)
	at org.apache.commons.csv.CSVParser.getRecords(CSVParser.java:628)
	at org.casbin.jcasbin.util.Util.splitCommaDelimited(Util.java:236)
```
Here is the policy file:
```
p, user, /data1, read, {"Equals":{"seller_id":"123", "corp":"CompanyA"}}
```
Without comma in json, it could work fine
```
p, user, /data1, read, {"Equals":{"seller_id":"123"}}
```
I have tried several solutions but they still do not work.
such as
```
p2, user, /data1, read, {""Equals"":{""seller_id"":""123"", ""corp"":""CompanyA""}}
p2, user, /data1, read, "{""Equals"":{""seller_id"":""123"", ""corp"":""CompanyA""}}"

```
I also checked the issues: https://github.com/casbin/jcasbin/issues/158 & https://github.com/casbin/jcasbin/issues/184 but the result is still the same.

Could you please help with this?

**Comment by hsluoyz** [comment]
@seriouszyx can you take a look?

**Comment by seriouszyx** [comment]
@huyphan-tiki  Please provide the conf file.

**Comment by huyphan-tiki** [comment]
@seriouszyx Sorry about this missing. Here is my conf
```
[request_definition]
r = sub, obj, act
r2 = sub, obj, act, attributes

[policy_definition]
p = sub, obj, act
p2= sub, obj, act, condition

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
#RABC
m = g(r.sub, p.sub) && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
#ABAC
m2 = g(r2.sub, p2.sub) && isMatch(r2.attributes, p2.condition) && regexMatch(r2.obj, p2.obj) && regexMatch(r2.act, p2.act)
```
`isMatch` is a custom function I wrote from https://lodash.com/docs/4.17.15#isMatch, which handles JSON string in the policy rules

**Comment by seriouszyx** [comment]
@huyphan-tiki The exception is caused by [this line](https://github.com/casbin/jcasbin/blob/64b984d5885cf5d4be72c0482de8706ba0025476/src/main/java/org/casbin/jcasbin/persist/Helper.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L37) when loading policy data from the adapter. It uses method [splitCommaDelimited](https://github.com/casbin/jcasbin/blob/64b984d5885cf5d4be72c0482de8706ba0025476/src/main/java/org/casbin/jcasbin/util/Util.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L236) to split a comma-delimited string. I have a solution which makes CSVParser support the escape character `\`. Then you can save your policy data as below.

```csv
p2, user, /data1, read, {"Equals":{"seller_id":"123"\, "corp":"CompanyA"}}
```

If there is no question, I will open a PR. But I'm not sure whether this will cause other problems or not. @hsluoyz

**Comment by huyphan-tiki** [comment]
Thanks @seriouszyx , I think it will be ok. As I understand, we will use the escape character `\` for any special characters that I want to be escaped in csv format at policy rules ?

Example, If I want to get raw string 
```
{"Equals":{"seller_id":"123", "corp":"CompanyA"}}
```
Should I put in policy rule like this
```
{"Equals":{"seller_id":"123"\, "corp":"CompanyA"}}
```
Or like this
```
{\"Equals\":{\"seller_id\":\"123\"\, \"corp\":\"CompanyA\"}}
```
Because the character `"` double quote is also a special character in csv format

Hope to get your answer soon.
Thanks

**Comment by hsluoyz** [comment]
@huyphan-tiki @seriouszyx after a second look, shouldn't we follow the CSV standardized escape rule? If we want to escape a CSV element, we will wrap the content with double quotes. The double quote itself inside double quotes can be escaped by two quotes. See more details at: https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv

I think we should follow the CSV standard.

**Comment by huyphan-tiki** [comment]
Hi @hsluoyz ,

First, as I have mentioned in the issue's description, I have tried many CSV standardized escape rules as below but they have not still worked
```
p2, user, /data1, read, "{""Equals"":{""seller_id"":""123"", ""corp"":""CompanyA""}}"
p2, user, /data1, read, "{""Equals"":{""seller_id"":""123"" "," ""corp"":""CompanyA""}}"
p2, user, /data1, read, "{""Equals"":{""seller_id"":""123"" ", ""corp"":""CompanyA""}}"
p2, user, /data1, read, {"Equals":{"seller_id":"123" ", "corp":"CompanyA"}}
```
In @seriouszyx 's comment, It uses method `splitCommaDelimited` to split a comma-delimited string and the CSVParser can not recognize the `"` double-quote escape character.

Second, I am using DB, not CSV for policy rules and it's still using [this method](https://github.com/casbin/jcasbin/blob/64b984d5885cf5d4be72c0482de8706ba0025476/src/main/java/org/casbin/jcasbin/persist/Helper.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L28). 

Please correct me if I was wrong.
Thanks

**Comment by hsluoyz** [comment]
@huyphan-tiki OK then.

@seriouszyx
