### ISSUE TITLE
Use the new jCasbin POM, null pointer

### ISSUE THREAD

**Issue by Memory63** [casbin/jcasbin#246]
https://blog.csdn.net/waynelee0809/article/details/85702551

Modeled after the program written by this blog, the jCasbin version of this blog is 1.1.0. Jcasbin upgrade 1.21.0, jDBC-jcasbin upgrade 2.1.3. And then submitted to the NullPointerException

The line in the image is NullPointerException

The picture
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/35125750/145026420-85515f94-c017-4092-bb75-4863d97dc87e.png">

**Comment by hsluoyz** [comment]
@seriouszyx plz take a look

**Comment by Memory63** [comment]
The jDBC-jCasbin version should be 2.0.0

**Comment by hsluoyz** [comment]
@Abingcbc can you take a look at this one?
