### ISSUE TITLE
Inconsistent behavior while updating policy

### ISSUE THREAD

**Issue by sojanm28** [casbin/jcasbin#255]
Hello,

I am seeing inconsistent behavior when I am trying to update the grouping policy by using the below methods

```java
// remove old mapping
removeFilteredNamedGroupingPolicy(String ptype, int fieldIndex, String... fieldValues);
// add the new one
addNamedGroupingPolicy(String ptype, String... params);
```

3 out of 4 times this work, but addNamedGroupingPolicy() fails to reflect the updated values in the casbin policy mapper.

Any help/insights will be greatly appreciated

Thanks!

**Comment by hsluoyz** [comment]
@seriouszyx @abichinger @Abingcbc

**Comment by 553269487** [comment]
Hi there! Usually it should be a multithread bug. But i have checked the source code they put lock on the mapper. Did you use your own multithread maybe?

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@sojanm28 Can I have your code about this bug?

**Comment by tangyang9464** [comment]
@hsluoyz No response for too long, should be closed.
