### ISSUE TITLE
bottleneck with loadPolicy usage

### ISSUE THREAD

**Issue by sojanm28** [casbin/jcasbin#256]
It seems LoadPolicy() is a bottleneck. How can Casbin be scaled if there are large number of users and each user has multiple policies?. And if a single policy is updated, LoadPolicy has to be invoked?. Is there a better way to approach it?
x: a users permission get updated and without loading the entire policy set there's currently no way to detect that change?

**Comment by hsluoyz** [comment]
See: https://casbin.org/docs/en/performance
