### ISSUE TITLE
Does jcasbin need to manually load the policy before each authorization?

### ISSUE THREAD

**Issue by yicm** [casbin/jcasbin#257]
**my use case:**

- Microservices: 
    - gateway: only for authorization
    - user_role_permission_management: policy management
- Cluster: Authentication service has multiple replicas

**questions:**

- gateway can not get the newest policy when policy updated, can not be dynamically authenticated
- The policy needs to be loaded before each authentication. Is there a better way?

**Comment by tangyang9464** [comment]
@yicm You need to use [watcher](https://casbin.org/docs/en/watchers), which is automatically loaded policy when the policy is updated.

**Comment by hsluoyz** [comment]
@yicm see: https://casbin.org/docs/en/performance
