### ISSUE TITLE
Delete the group API interface bug

### ISSUE THREAD

**Issue by Memory63** [casbin/jcasbin#277]
When using this interface enforcer. RemoveNameGroupingPolicy (" g ", "role1") to delete group, database data deleted successfully, but cached data is still there.

### POM
```
<dependency>  
      <groupId>org.casbin</groupId>
      <artifactId>jcasbin</artifactId>
      <version>1.21.0</version>
</dependency>
<dependency>
      <groupId>org.casbin</groupId>
      <artifactId>jdbc-adapter</artifactId>
      <version>2.2.1</version>
</dependency>
```

### Execute Code
![image](https://user-images.githubusercontent.com/35125750/171542363-768c3207-2b64-4120-8b94-159ecbb3c91b.png)

### Adapter
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/35125750/171542218-8c852356-acd1-4181-acf5-2ac1bcd48e4c.png">

### Datebase & Cache
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/35125750/171542292-469dd1bf-92c9-4fdf-93ee-f900226f643d.png">

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by imp2002** [comment]
**remove rules in the database：**[code impl url](https://github.com/jcasbin/jdbc-adapter/blob/98a9aa8e48ea747f4b5128d74a1a2b9072ab562d/src/main/java/org/casbin/adapter/JDBCBaseAdapter.java#L411)

![image](https://user-images.githubusercontent.com/41513919/171822450-da324843-1b3c-49b7-bef7-708ca513818e.png)

**remove rules in the Redis：** [code impl url](https://github.com/jcasbin/redis-adapter/blob/686bc3e769459ba1f4f98c4ffa519655450010b3/src/main/java/org/casbin/adapter/RedisAdapter.java#L91)
![image](https://user-images.githubusercontent.com/41513919/171822479-a29dfc88-9ca4-4e24-b911-12c3d3d56369.png)

When rule incomplete, like above input `role1`, it will delete success in database, but false in Redis. it matches the data in database `(role1, role2)` and `(role1, role3)`, but didn't in Redis,
In Redis if you want to remove `(role1, role2)`, the input must be `(role1, role2)` too.

**Comment by hsluoyz** [comment]
@Memory63 which adapter do you use?

**Comment by Memory63** [comment]
> @Memory63 which adapter do you use?

JDBC. It's in the screenshot.

**Comment by Memory63** [comment]
> 

It feels strange when a delete succeeds in the database while the cache is still in place.

**Comment by hsluoyz** [comment]
@Memory63 if you want to delete policy with a partial condition, you should use the "Filtered" API: `RemoveFilteredNamedGroupingPolicy()`: https://casbin.org/docs/en/management-api#removefilterednamedgroupingpolicy . `RemoveNameGroupingPolicy()` is only for matching all fields for a policy.

**Comment by Memory63** [comment]
@hsluoyz 
RemoveFilteredNamedGroupingPolicy, the use of this API is no problem. RemoveNameGroupingPolicy is a full field match and is fine.
However, the problem I feedback is that since the API parameters do not match, the data is also deleted, and only the database data is deleted. The cached data is not deleted, which is problematic, causing data consistency problems.

**Comment by hsluoyz** [comment]
@tangyang9464 @imp2002

**Comment by imp2002** [comment]
Yes, it's a bug, in `jdbc-adapter` the `RemoveNameGroupingPolicy()` implements with `RemoveFilteredNamedGroupingPolicy` directly, it leads to the wrong result.


code ref: https://github.com/jcasbin/jdbc-adapter/blob/98a9aa8e48ea747f4b5128d74a1a2b9072ab562d/src/main/java/org/casbin/adapter/JDBCBaseAdapter.java#L373-L378
![image](https://user-images.githubusercontent.com/41513919/172199207-989ead52-9d33-4330-8d65-01cdd85a882e.png)

**Comment by hsluoyz** [comment]
@imp2002 I don't think your pasted code has bug. It means to match all the fields in the filter, it is what `removePolicy()` should do: match all fields.

@tangyang9464 you wrote this part of code, what do you say?

**Comment by tangyang9464** [comment]
@Memory63 First of all your usage is wrong, and at the same time the implementation of ``jdbc-adapter`` is wrong. ``removeNamedGroupingPolicy`` only matches a complete policy record. (params should be``role1, role2``) You should use removeFilteredPolicy to filter policy by some conditions. (params should be ``role1``)

**Comment by Memory63** [comment]
@tangyang9464 
Yes, I did use it wrong. But the deletion did succeed, and even weirder, only the database was deleted, not the cache. I feel that this logic is wrong, you will either succeed in deleting or you will fail, regardless of the usage and input.
Besides, my English is poor, so I don't know whether the translation software I use can correctly convey my meaning.
I hope I can understand the meaning of my expression.

**Comment by tangyang9464** [comment]
@Memory63 As I said above, the implementation of ``jdbc-adapter`` is wrong. We will fix it later. Could you @imp2002  fix it?

**Comment by imp2002** [comment]
OK, i will fix it.
