### ISSUE TITLE
Remove guava

### ISSUE THREAD

**Issue by i1619khz** [casbin/jcasbin#279]
I searched for the use of guava in the jcasbin code and found only in used in Util.java. Only used for md5 encryption

https://github.com/casbin/jcasbin/blob/a21b2199bcd1199a66aebf7e86930b2218dfacd1/src/main/java/org/casbin/jcasbin/util/Util.java#L45

https://github.com/casbin/jcasbin/blob/a21b2199bcd1199a66aebf7e86930b2218dfacd1/src/main/java/org/casbin/jcasbin/util/Util.java#L292-L295

Referring to the practice of common codec, only need to jdk
```java
  public static MessageDigest getDigest(String algorithm) {
      try {
          return MessageDigest.getInstance(algorithm);
      } catch (NoSuchAlgorithmException e) {
          throw new IllegalArgumentException(e);
      }
  }

  public static String md5(String data) {
      return new String(getDigest("MD5").digest(data.getBytes(StandardCharsets.UTF_8)));
  }
```
Reduce unnecessary dependencies

**Comment by tangyang9464** [comment]
@i1619khz Could you make a PR？

**Comment by i1619khz** [comment]
> @i1619khz可以做PR吗？

with pleasure

**Comment by i1619khz** [comment]
> @i1619khz Could you make a PR？
#280

**Comment by i1619khz** [comment]
@tangyang9464 #280
