### ISSUE TITLE
Why use the first one when there are multiple [policy_effects]

### ISSUE THREAD

**Issue by 2140345** [casbin/jcasbin#284]
Model:

```ini
[request_definition]
r = sub, obj, act
r2 = sub, obj, act

[policy_definition]
p = sub, obj, act
p2 = sub_rule, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))
e2 = some(where (p.eft == allow))

[matchers]
#RABC
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
#ABAC
m2 = eval(p2.sub_rule) && r2.obj == p2.obj && r2.act == p2.act
```

The following is the java test code:

```java
@Test
    public void testMultiplePolicyDefinitions() {
        Enforcer e = new Enforcer("examples/multiple_policy_definitions_model.conf", "examples/multiple_policy_definitions_policy.csv");
        EnforceContext enforceContext = new EnforceContext("2");
        enforceContext.seteType("e");
        testEnforce(e, "alice", "data2", "read", true);
        testEnforceWithContext(e, enforceContext, new AbacAPIUnitTest.TestEvalRule("alice", 70), "/data1", "read", false);
        testEnforceWithContext(e, enforceContext, new AbacAPIUnitTest.TestEvalRule("alice", 30), "/data1", "read", true);
    }
```

I want to use  enforceContext.seteType("e2"), but I can only use e.
Because the push in the defaultstreameffector class threw an unsupported operation exception
seek help!

**Comment by hsluoyz** [comment]
@imp2002 

/cc @tangyang9464

**Comment by imp2002** [comment]
@2140345 I'm ok for this. Could you provide your INFO log?

![image](https://user-images.githubusercontent.com/41513919/178494803-50bd9a9c-ab96-4644-a0dd-5c05ce969bdc.png)
![image](https://user-images.githubusercontent.com/41513919/178494853-c1c0ce0e-22eb-4ad4-b6cf-8e000547d9c4.png)

**Comment by 2140345** [comment]
> @2140345我没关系。你能提供你的信息日志吗？
> 
> ![图片](https://user-images.githubusercontent.com/41513919/178494803-50bd9a9c-ab96-4644-a0dd-5c05ce969bdc.png) ![图片](https://user-images.githubusercontent.com/41513919/178494853-c1c0ce0e-22eb-4ad4-b6cf-8e000547d9c4.png)


This is a version problem. When I upgraded the version of jcaspen to 1.24.2, the problem was solved.

**Comment by 2140345** [comment]
@imp2002 我把版本升级到1.24.2之后就没有这个问题了，当时是用了老的版本。

**Comment by 2140345** [comment]
The problem has been solved. Thank you！
