### ISSUE TITLE
How to work on the springboot？

### ISSUE THREAD

**Issue by toop** [casbin/jcasbin#286]
On the springboot, when a user accesses /books/list, I need to filter books data according to the data_scope range data of the currently logged in user and the category value of books. Please ask how to do this. Please give some collective examples. Thank you very much!

USER：

user | dept | data_scope
admin | 1 | [,]
Tom | 1 | [1,2,3]
Sim | 2 | [1,2]
Kat | 3 | null

BOOKS：

id | name | category
1 | book1 | 1
2 | book2 | 1
3 | Book3 | 2
4 | book4 | 3
5 | book5 | 4
6 | book6 | 5

when user admin to access the api /books/list, can visible all data，return the data:

id | name | category
1 | book1 | 1
2 | book2 | 1
3 | Book3 | 2
4 | book4 | 3
5 | book5 | 4
6 | book6 | 5

when user Tom to access the api /books/list, books.category in user.data_scope, return the data:
id | name | category
1 | book1 | 1
2 | book2 | 1
3 | Book3 | 2
4 | book4 | 3

when user Sim to access the api /books/list, books.category in user.data_scope, return the data:
id | name | category
1 | book1 | 1
2 | book2 | 1
3 | Book3 | 2

when user Kat to access the api /books/list, user.data_scope is null, return the exception:
“access denied，missing permissions”

How to implement the above requirements in MVC and oauth2 environment? Please give some practical examples. Thank you very much!

**Comment by imp2002** [comment]
It is not work on the table `user` above. What you need do is store the policy like
![image](https://user-images.githubusercontent.com/41513919/181274452-7af27548-4085-4373-8801-948ab76f654f.png)

See how to add policy and how to persistence in db.
policy store doc:
https://casbin.org/docs/en/policy-storage

RBAC Doc:
https://casbin.org/docs/en/rbac

Vedio:
https://www.jtthink.com/course/play/2706

**Comment by toop** [comment]
Thank you very much for your reply and solution!
