### ISSUE TITLE
batch enforce is too slow.

### ISSUE THREAD

**Issue by dijiekstra** [casbin/jcasbin#289]
I use jcasbin 1.22.3 at prod env .
We have 20000+ policies, and per query has 200+ resource need to been check .
Query will done at least 1s, how can i to improve it ?

**Comment by dijiekstra** [comment]
And i use jprofile to look up slow code , i found query has 80% time to execute `expression.execute()`

**Comment by hsluoyz** [comment]
@dijiekstra provide:

- Model
- Policy
- Request
- Result

**Comment by hsluoyz** [comment]
Closed as stale
