### ISSUE TITLE
EnforceEx support in jcasbin

### ISSUE THREAD

**Issue by jwanggg** [casbin/jcasbin#297]
Is it possible to get support for getting a reason for why the enforce method fails https://github.com/casbin/casbin/blob/66bb7027b73c102e17f77ffd429e50bd555bf035/enforcer_synced.go#L166 implemented for jcasbin?

**Comment by hsluoyz** [comment]
See Go's EnforceEx: https://github.com/casbin/casbin/issues/606#issuecomment-782614618 , we need to port it to Java

**Comment by hsluoyz** [comment]
@imp2002
