### ISSUE TITLE
is there a thread safe problem?

### ISSUE THREAD

**Issue by DaiZZZZZ** [casbin/jcasbin#30]
call **Enforcer::loadPolicy()** and **Enforcer::enforce()** concurrently may lead to wrong result

**Comment by hsluoyz** [comment]
Hi @DaiZZZZZ ,

Yes. Those functions are NOT thread-safe. As you can see in Golang Casbin, we have defined the synced version enforcer: https://github.com/casbin/casbin/blob/ccd536f4ce692763de9459f1cfb8889bf4df16cd/enforcer_synced.go#L102-L107

If we want to add synced version enforcer to jCasbin, which synchronization mechanism do you prefer in Java to implement it?

**Comment by hsluoyz** [comment]
Hi @fangzhengjin , can you help solve this issue?

**Comment by DaiZZZZZ** [comment]
> Hi @DaiZZZZZ ,
> 
> Yes. Those functions are NOT thread-safe. As you can see in Golang Casbin, we have defined the synced version enforcer: https://github.com/casbin/casbin/blob/ccd536f4ce692763de9459f1cfb8889bf4df16cd/enforcer_synced.go#L102-L107
> 
> If we want to add synced version enforcer to jCasbin, which synchronization mechanism do you prefer in Java to implement it?

ReadWriteLock is ok

**Comment by hsluoyz** [comment]
Hi @DaiZZZZZ , this issue has been fixed in: https://github.com/casbin/jcasbin/pull/32 . Please use ``SyncedEnforcer`` instead.

**Comment by DaiZZZZZ** [comment]
ok, thx
