### ISSUE TITLE
[Feature] Implement subjectPriority in jcasbin

### ISSUE THREAD

**Issue by coffeeZhang001** [casbin/jcasbin#301]
I am usring casbin with jcasbin library, but i found the [[load-policy-with-priority-based-on-role-and-user-hierarchy](https://casbin.io/docs/priority-model#load-policy-with-priority-based-on-role-and-user-hierarchy)]  feature is not implementd in jcasbin.

I think this feature is valuable and convenient when we want to define policy with priority. 

Currently, i have to define priority for each policy like this:
```
p, 10, data1_deny_group, data1, read, deny
p, 10, data1_deny_group, data1, write, deny
```

**Comment by TraMiu** [comment]
Yes, I think this feature is important too.

**Comment by imp2002** [comment]
I will try sync this feature.

**Comment by Xhy-5000** [comment]
what's the usage of this mthod?https://github.com/casbin/casbin/blob/4028f8a8f4cf3ee76056da41bbd596ec97baac2a/model/model.go#L242

**Comment by Xhy-5000** [comment]
@imp2002 Do you know that?

**Comment by Xhy-5000** [comment]
[feat: Implement subject Priority in jcasbin #306](https://github.com/casbin/jcasbin/pull/306)
