### ISSUE TITLE
[Question] I want to get matching policy ,but  enforce(String matcher, List<String> explain, Object... rvals) is private。

### ISSUE THREAD

**Issue by 13276965576** [casbin/jcasbin#305]
I want to get matching policy ,but  enforce(String matcher, List<String> explain, Object... rvals) is private。
so,can modify this method to public?
private boolean enforce(String matcher, List<String> explain, Object... rvals)

**Comment by hsluoyz** [comment]
@imp2002

**Comment by 13276965576** [comment]
@hsluoyz thk，but i am using java can't use go api,
@casbin-bot java api can't get match policy in progress, enforceEx retrun is boolean paramter.
explain is match policy.
    public boolean enforceEx(Object... rvals) {
        List<String> explain = new ArrayList<>();
        return enforce("", explain, rvals);
    }
