### ISSUE TITLE
ArrayIndexOutOfBoundsException when combining ABAC and RBAC

### ISSUE THREAD

**Issue by TraMiu** [casbin/jcasbin#311]
I want to combine ABAC and RBAC models for my project and this is my initial model:
![image](https://user-images.githubusercontent.com/54165403/199044361-ec0ee915-a5bc-4977-ab70-0a4499018283.png)

Where I enforce sub and obj as Objects; act and targetProperty as String. This is my test:
![image](https://user-images.githubusercontent.com/54165403/199043952-48319b7b-1134-47b9-8867-b6c5b691c724.png)
As you can see, the **targetProperty** is one of the properties of the **obj** that I want to check if **sub** can **act** on it. 
And filters are the requirements for other properties of the **obj**. For example, supervisor can read gpa of students whose birth place is "hcm".

Here is how I store policy database in MySQL:
![image](https://user-images.githubusercontent.com/54165403/199039927-5112a654-669d-4a15-bd8f-bad8dcf7cff7.png)

However, it came up with this OutOfBoundsException although I can load the policy successfully.
![image](https://user-images.githubusercontent.com/54165403/199044610-b4e74769-c9e4-4774-a273-074ea2754185.png)

While debugging, I tried to reduce the size of the matcher (just checking if actions match)
![image](https://user-images.githubusercontent.com/54165403/199046518-b44e0fbc-100d-4dc6-9e50-1f9e482d9247.png)
When I use `e.enforce(bob, "read", "gpa", alice)` => the result was true. But when I use `e.enforce(bob, "eat", "gpa", alice)` => the result was still the above error.

I have tried the examples for ABAC and RBAC models and they worked on my computer, but not this combined model. 
Could you show me a way to debug this or a better way to combine RABC and ABAC models? 

Tell me if you need more information.
Thank you

**Comment by hsluoyz** [comment]
@imp2002 @Xhy-5000

**Comment by OutOfEastGate** [comment]
Thank you for your feedback. I've found the reason.
![image](https://user-images.githubusercontent.com/101807499/200315906-c044d4ea-1992-4a37-813a-f626c897e169.png)

As shown in the figure, the array initialization is three because of the vacancy of v0, but there are four when assigning values. I will solve this problem immediately.

**Comment by OutOfEastGate** [comment]
@TraMiu Thank you for your feedback. I've found the reason.
![picture](https://user-images.githubusercontent.com/101807499/200315906-c044d4ea-1992-4a37-813a-f626c897e169.png)
As shown in the figure, the array initialization is three because of the vacancy of v0, but there are four when assigning values. I will solve this problem immediately

**Comment by OutOfEastGate** [comment]
> 
@TraMiu 
![picture](https://user-images.githubusercontent.com/101807499/200315906-c044d4ea-1992-4a37-813a-f626c897e169.png)
Can you tell me how this null value is generated? And what adapter did you use?

**Comment by OutOfEastGate** [comment]
> I want to combine ABAC and RBAC models for my project and this is my initial model: ![image](https://user-images.githubusercontent.com/54165403/199044361-ec0ee915-a5bc-4977-ab70-0a4499018283.png)
> 
> Where I enforce sub and obj as Objects; act and targetProperty as String. This is my test: ![image](https://user-images.githubusercontent.com/54165403/199043952-48319b7b-1134-47b9-8867-b6c5b691c724.png) As you can see, the **targetProperty** is one of the properties of the **obj** that I want to check if **sub** can **act** on it. And filters are the requirements for other properties of the **obj**. For example, supervisor can read gpa of students whose birth place is "hcm".
> 
> Here is how I store policy database in MySQL: ![image](https://user-images.githubusercontent.com/54165403/199039927-5112a654-669d-4a15-bd8f-bad8dcf7cff7.png)
> 
> However, it came up with this OutOfBoundsException although I can load the policy successfully. ![image](https://user-images.githubusercontent.com/54165403/199044610-b4e74769-c9e4-4774-a273-074ea2754185.png)
> 
> While debugging, I tried to reduce the size of the matcher (just checking if actions match) ![image](https://user-images.githubusercontent.com/54165403/199046518-b44e0fbc-100d-4dc6-9e50-1f9e482d9247.png) When I use `e.enforce(bob, "read", "gpa", alice)` => the result was true. But when I use `e.enforce(bob, "eat", "gpa", alice)` => the result was still the above error.
> 
> I have tried the examples for ABAC and RBAC models and they worked on my computer, but not this combined model. Could you show me a way to debug this or a better way to combine RABC and ABAC models?
> 
> Tell me if you need more information. Thank you

@TraMiu  
This problem is caused by the fact that the eval expression is null. When defining the policy, you should assign a default value (true or false) to the eval expression so that OutOfBoundsException does not appear.

**Comment by TraMiu** [comment]
I got it now, thank you very much! 
In addition, I am working on the case where I have **multiple object types** and I **stored all of the policies for those object in the same adapter.**
For example, if I have a new **DummyResource** here that does not have the `.birthPlace` attribute like object **Student**
![image](https://user-images.githubusercontent.com/54165403/201500633-e1bd188b-d275-496c-8d6b-8db14c4c16dc.png)
This exception will occur:
`Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find variable r_obj.birthPlace
`
I tried to workaround this situation by adding a new column (**the resource role**) to the database and checking the **user roles** and  **resource roles** before evaluating the **sub_rule** in the matcher 
![image](https://user-images.githubusercontent.com/54165403/201501065-ac583d5a-1695-44d3-80f7-bf042b5dd477.png)
Hoping that if the resource roles does not match, the matcher will skip that policy, so that the exception will not occure. However, it did not work.

Is there a better way to address this or I should have **different enforcers for different object types**?

**Comment by hsluoyz** [comment]
@TraMiu plz create a new issue for a new question
