### ISSUE TITLE
ABAC for multiple Object Types

### ISSUE THREAD

**Issue by TraMiu** [casbin/jcasbin#315]
I am working on the case where I have **multiple object types** and I **stored all of the policies for those object in the same adapter.**
For example, if I have a new **DummyResource** here that does not have the `.birthPlace` attribute like object **Student** (mentioned in #311)
![image](https://user-images.githubusercontent.com/54165403/201500633-e1bd188b-d275-496c-8d6b-8db14c4c16dc.png)
When I use `e.enforce(bob, "read", "gpa", dummy)`, the enforcer went through policies for object **Student** and end up getting this exception:
`Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find variable r_obj.birthPlace
`
Policy for object **Student**:
![image](https://user-images.githubusercontent.com/54165403/199039927-5112a654-669d-4a15-bd8f-bad8dcf7cff7.png)

I tried to workaround this situation by adding a new column (**the resource role**) to the database and checking the **user roles** and  **resource roles** before evaluating the **sub_rule** in the matcher 
![image](https://user-images.githubusercontent.com/54165403/201501065-ac583d5a-1695-44d3-80f7-bf042b5dd477.png)
Hoping that if the resource roles does not match, the matcher will skip that policy, so that the exception will not occur. However, it did not work.

Is there a better way to address this or I should have **different enforcers for different object types**?

**Comment by hsluoyz** [comment]
@OutOfEastGate

**Comment by imp2002** [comment]
>Hoping that if the resource roles does not match, the matcher will skip that policy

The matcher can't skip rule, `&&` in `[matchers]` is not short-circuit operator. Different enforcers for different object types is a good way.

**Comment by OutOfEastGate** [comment]
> Is there a better way to address this or I should have **different enforcers for different object types**?
If the parameter you pass in does not have the field 'birthPlace'', the eval you defined will report an error in this case. You can refer to this link to define a p2 strategy to adapt to situations without 'birthPlace'.  [policy-definition](https://casbin.org/docs/en/syntax-for-models#policy-definition)

**Comment by OutOfEastGate** [comment]
> Is there a better way to address this or I should have **different enforcers for different object types**?

If the parameter you pass in does not have the field 'birthPlace'', the eval you defined will report an error in this case. You can refer to this link to define a p2 strategy to adapt to situations without 'birthPlace'. [policy-definition](https://casbin.org/docs/en/syntax-for-models#policy-definition)

**Comment by TraMiu** [comment]
Oke, I got it. I will try it out.
