### ISSUE TITLE
while I try to remove group from casbin, only the data in memory is deleted, it still exist in mysql

### ISSUE THREAD

**Issue by yu-hailong** [casbin/jcasbin#316]

**Comment by yu-hailong** [comment]
1. create policy , it is normal : I can find it in memory and mysql
2. I try to remove them using
   enforcer.removeFilteredNamedPolicy(pType,0,e);
   enforcer.removeGroupingPolicy(id, parentId); 
remove p and g policy, but I found the data in memory is removed, but the data in mysql is still there

3. version info:

 
        <dependency>
            <groupId>org.casbin</groupId>
            <artifactId>jcasbin</artifactId>
            <version>1.21.0</version>
        </dependency>
        <dependency>
            <groupId>org.casbin</groupId>
            <artifactId>jdbc-adapter</artifactId>
            <version>2.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.casbin</groupId>
            <artifactId>jcasbin-redis-watcher</artifactId>
            <version>1.4.1</version>
        </dependency>

**Comment by hsluoyz** [comment]
@imp2002 @OutOfEastGate

**Comment by imp2002** [comment]
It's has been fixed in https://github.com/jcasbin/jdbc-adapter/pull/50. Try `jdbc-adapter` lastest version.
