### ISSUE TITLE
Combine RBAC with domain and keymatch 

### ISSUE THREAD

**Issue by Harishs27** [casbin/jcasbin#331]
My application is cloud app with multiple tenants/domain
I want to use the RBAC with domain combining with keyMatch model, but there is no examples or documents available in java.

My Use case is as below:

```bash
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom &&  keyMatch(r.obj == p.obj) && keyMatch(r.act == p.act) 
```
Data:

```bash
p, ADMINROLE, domain1, ADMIN, USER_READ
p, ADMINROLE, domain1, ADMIN, USER_EDIT
p, ADMINROLE, domain1, ADMIN, USER_DELETE
p, ADMINROLE, domain1, ADMIN, USER_ADD
p, ADMINROLE, domain1, https://*/userMgmt/User*?*, GET
p, ADMINROLE, domain1, https://*/userMgmt/User*?*, PUT

g, user1, ADMINROLE, domain1
```

I want to validate if the user has permission to perform GET | PUT on api resource

Eg:
A user(USER1) with role ADMINROLE can perform below operation
  
   sub: ADMINROLE
   obj: domain1
   obj: https://{{url}}/userMgmt/User/1 
   act: PUT
   This validate permission should be **true** as user can perform put on api

   sub: ADMINROLE
   obj: domain1
   obj: https://{{url}}/userMgmt/User/1 
   act: DELETE
   This validate permission request should be **false** as user cannot perform DELETE on api

I tried testing by using enforcer like below on the domain
Enforcer e = new Enforcer("casbin_model.conf")
e.enforcer("ADMINROLE", "domain1", "https://{{url}}/userMgmt/User/1", "PUT");

However i am getting the error as 
```bash 
java.lang.IllegalArgumentException: Wrong number of args (1) passed to: keyMatch
```

Suggest me approach(code snippet) if any where i can directly test if user has resource permission

Tell me if you need more information.

Thank u.

**Comment by nikhilgotpagar** [comment]
Hi Assign me this issue please

**Comment by longxu0509** [comment]
Your model.conf file has a problem with the keyMatch function, which should be separated by commas instead of ==.
[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom &&  keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)
