### ISSUE TITLE
issue about ABAC for multiple and dynamic attribute object

### ISSUE THREAD

**Issue by lissali** [casbin/jcasbin#332]
I am working on the case where request object has multiple and dynamic attributes, also  my policy and model are as following.
When try to enforce, seems check policy one by one, 
example1: request with object {role:"admin} , instance/db, *, CREATE--- pass
example2: request with object {isManager:"true"},  instance/db, /level1/level2, INSERT --- failed with error:
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find variable r_sub.role
 
Policy:

```csv
p, r.sub.role=='admin', instance/db, *, (CREATE)|(DROP)|(INSERT)|(DELETE)|(SELECT)|(USE)|(SHOW)
p, r.sub.role=='user', instance/db, *, (SELECT)|(USE)|(SHOW)
p, r.sub.isManager=='true', instance/db, /level1/level2, INSERT
```

Model.conf

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p= name, sub_rule, dom, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
#ABAC
m = eval(p.sub_rule) && r.dom == p.dom && keyMatch(r.obj.URL, p.obj) && regexMatch(r.act, p.act)
```

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by imp2002** [comment]
Verified, I will fix it.
