### ISSUE TITLE
[Feature] Implement WatcherEx 

### ISSUE THREAD

**Issue by imp2002** [casbin/jcasbin#340]
No `WatcherEx` has been implemented for jCasbin.
 
Ref: https://casbin.org/zh/docs/watchers#watcherex

Implemented for Go-Casbin can be used as a reference:
https://github.com/casbin/redis-watcher
https://github.com/IguteChung/casbin-psql-watcher
![image](https://github.com/casbin/jcasbin/assets/41513919/51164744-aab5-4e21-93a4-3f1cf4655ee2)

**Comment by hsluoyz** [comment]
@PokIsemaine
