### ISSUE TITLE
Casbin with Graalvm native breaks since 1.32.0

### ISSUE THREAD

**Issue by bvmanuelpaillafil** [casbin/jcasbin#346]
Hi all,

Im using casbin with:

- GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
- Quarkus 3.1.2.Final
- Maven 3.9.2

The project have a native-build(and run) powered by graalvm feature, but the output binary/executable breaks when use casbin 1.32.0 or higher with this error:

<img width="702" alt="imagen" src="https://github.com/casbin/jcasbin/assets/102039072/2aa9dd67-39a6-4bdf-8b0d-82389f2b4862">

When downgrade to jcasbin 1.31.4 the native binary its run ok.

We have to execute a little research to try finding the text "Fail to load internal modules." and match with this https://github.com/killme2008/aviatorscript/blob/20a3c7f432446861da28a67d5fdee7d959fcc05c/src/main/java/com/googlecode/aviator/AviatorEvaluatorInstance.java#L897C60-L897C60
We identify that jcasbin uses aviator plugin but with our-own-version of aviator plugin (org.casbin.aviator) with v5.1.4-fix and the latest version of com.googlecode.aviator dependency are 5.3.3. We think is issue is related with #264 

We attach a demo project to test it.
(for build native: mvn clean compile package -Pnative)

[code-with-quarkus-20230624_184253.zip](https://github.com/casbin/jcasbin/files/11858352/code-with-quarkus-20230624_184253.zip)

**Comment by D1zzzY1** [comment]
Hello, 
I configured according to the version number you provided and tested the demo you mentioned, but I did not encounter the problem you described.  Could you please provide more detailed information about the error, or could you try again to explain the issue?
![image](https://github.com/casbin/jcasbin/assets/107469948/e503aaba-766f-4753-871d-0a1e1252731e)
![image](https://github.com/casbin/jcasbin/assets/107469948/1fe8f2c8-b217-4551-ba74-8bdea545bdc3)
![image](https://github.com/casbin/jcasbin/assets/107469948/59c6bb04-8096-4dca-8540-eefa645bf7d3)
