### ISSUE TITLE
High risk vulnerability.

### ISSUE THREAD

**Issue by donbing007** [casbin/jcasbin#348]
[Cx78f40514-81ff](https://devhub.checkmarx.com/cve-details/Cx78f40514-81ff/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea)

jcasbin 1.33.1

`
Provides transitive vulnerable dependency maven:commons-collections:commons-collections:3.2.2
`
`Cx78f40514-81ff 7.5 Uncontrolled Recursion vulnerability pending CVSS allocation`

**Comment by hsluoyz** [comment]
@donbing007 hi, don't know how severe this issue will affect jcasbin yet, would you like to make a PR to update the dependency?

**Comment by hsluoyz** [comment]
jCasbin doesn't use the `commons-collections` dependency in pom.xml, so this security hole has nothing much to do with jCasbin. Closed here
