### ISSUE TITLE
Question: Is there a way to persist policy and model?

### ISSUE THREAD

**Issue by DemianTinkiel** [casbin/jcasbin#35]
Use case is that I have a program that takes a model and a policy path and to test it I'd like to be able to do something like

```java
Model m = newModel();
m.addDef("r", "r", "sub, obj, act");
m.addDef("p", "p", "sub, obj, act");
m.addDef("g", "g", "_, _");
m.addDef("e", "e", "some(where (p.eft == allow))");
m.addDef("m", "m", "g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act");

Enforcer e = new Enforcer(m);

e.addPermissionForUser("alice", "data1", "read");
Path modelURI = e.persistModel();
Path policyURI = e.persistPolicy();

assertTrue(new myProgram(modelURI, policyURI).isAuth("alice", "read"))
```

**Comment by hsluoyz** [comment]
Hi @DemianTinkiel , model can be loaded in 3 ways: https://casbin.org/docs/en/model-storage. But Casbin doesn't provide a way to save it to somewhere. But It's very easy for you to write a util function to do that by accessing the ``Model`` object.

The policy can be saved or loaded with adapters. I don't know what's ``policyURI``. But you need to implement an adapter to support your URI.

**Comment by DemianTinkiel** [comment]
Hi @hsluoyz, thanks for that. But I was thinking more in the lines of Model and Policy providing a toString method for their content. The adapters could the build on top of that?

**Comment by hsluoyz** [comment]
You can implement a ``toString()`` method for model.

**Comment by DemianTinkiel** [comment]
excellent. I'll do that + policy too

**Comment by hsluoyz** [comment]
I think here will be another PR, right?

**Comment by DemianTinkiel** [comment]
Yep. There will be one tomorrow morning.

**Comment by hsluoyz** [comment]
BTW, you can link your Email in [this commit](https://github.com/casbin/jcasbin/commit/820f8ab9f7e8f20d26b8ec57776d24ec13687258) with your GitHub account for more accurate contribution calculation.

**Comment by DemianTinkiel** [comment]
@hsluoyz thanks,  I'm just happy to help :smile: sorry for PR spam, merge conflict resolution in github is weird to me. #40 is ready when you are

**Comment by DemianTinkiel** [comment]
@hsluoyz  You closed the PR. Is that intentional? Do you want a new one?

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/jcasbin/commit/e3a28951550a184f2561da5c78156386f5364c28
