### ISSUE TITLE
CSV values escaped using \

### ISSUE THREAD

**Issue by pzet123** [casbin/jcasbin#356]
Escaping CSV values was discussed in #243 however the resolution in the end was to use `\` for escaping commas in CSV files. 

This causes an issue when trying to share policies between different versions of Casbin (e.g. Node-Casbin and jCasbin) which use double quotation marks to format values. This is the preferred technique described in [RFC4180](https://www.ietf.org/rfc/rfc4180.txt).

Is there any reason not to switch to the method of escaping CSV values described in RFC4180?

**Comment by hsluoyz** [comment]
@pzet123 hi, can you make a PR?

**Comment by hsluoyz** [comment]
@pzet123 any update?

**Comment by pzet123** [comment]
Submitted PR
