### ISSUE TITLE
When using transactions, is it possible to provide an appending method instead?

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [casbin/jcasbin#388]
![image](https://github.com/casbin/jcasbin/assets/128599027/e12888ab-15cc-48b0-8922-bd88dda82390)
This approach would overwrite the original database rather than appending to it, meaning that if there are many user registrations, each new user's data would overwrite the existing data. When using transactions, is it possible to provide an appending method instead?

**Comment by hsluoyz** [comment]
@LetAmericaGreatAgain two ways:

1. You call addRole first, and check its result, if added successfully, then call addPolicy (aka manually maintain transaction)
2. You manipulate the DB directly without using Casbin API. The DB format for Casbin is very simple. You can do that by yourself.

**Comment by LetAmericaGreatAgain** [comment]
"Don't you think I already know that? What I want is for this framework to provide better transactional support at the framework level."

**Comment by hsluoyz** [comment]
@LetAmericaGreatAgain then can you give some advice about how to implement this feature? Or what kind of transaction API you would like to have?
