### ISSUE TITLE
  jcasbin EnableAcceptJsonRequest

### ISSUE THREAD

**Issue by 170120010123** [casbin/jcasbin#389]
It cannot be used in jcasbin

**Comment by LMay001** [comment]
it can be used in jcasbin
field "acceptJsonRequest" and method "enableAcceptJsonRequest" is designed in CoreEnforcer.java
the test case "testABACJsonRequest" in ModelUnitTest.java use it

**Comment by hsluoyz** [comment]
@170120010123 your jCasbin version is too low. Upgrade to latest
