### ISSUE TITLE
Dont see any user interactions in casbinJsGetPermissionForUser method

### ISSUE THREAD

**Issue by z0mb1ek** [casbin/jcasbin#395]
Hi, there is parameter in method named `user`, for what purposes is it needed there? method always returns the same thing

**Comment by z0mb1ek** [comment]
moreover in go library i see [`model.GetPolicy("g", ptype)`](https://github.com/casbin/casbin/blob/master/frontend.go#L42C20-L42C47)
I think it should be in java too.

**Comment by hsluoyz** [comment]
We should port the latest Go Casbin code to jCasbin
