### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by rajp33** [casbin/jcasbin#399]
I believe a fix was put out a while ago for ConcurrentModificationExceptions being thrown. We still see some being thrown here and there. Don't have much to go off of besides a stacktrace though. Not able to consistently reproduce it

<img width="1031" alt="Screenshot 2024-06-15 at 11 38 22 PM" src="https://github.com/casbin/jcasbin/assets/44758822/f7cba845-4923-4559-89cf-b9e03920741f">

**Comment by nodece** [comment]
Default enforce is non-thread-safe, you can switch to SyncedEnforcer, or you add a loading request to the single thread to avoid the concurrent issue.
