### ISSUE TITLE
Memory consumption during enforce method

### ISSUE THREAD

**Issue by Danneborg** [casbin/jcasbin#409]
We are using enforce( 1.22.6 version jcabin) method in our system and observing strange memory consumption. We upload around 3200 politics when the app is starting. When I call enforce method I see, that my app consumes around 700mb of heap memory, which I think quite strange. 
![image](https://github.com/user-attachments/assets/757be486-1674-463d-84b9-364783bc0b6a)
Also, sometimes my app is falling with OOM, we have 2 pods and each consumes more than 10GB of memory!
![image](https://github.com/user-attachments/assets/e1540db6-20a1-4ff8-b2d8-b9ac0c95a8be)
I used many heap dump analyzers and found that the most suspicious object belongs to com.googlecode.aviator.utils.Env library, it takes from 30% to 70% of my heap! 
![image](https://github.com/user-attachments/assets/e425767f-0ba8-41db-841c-eb49ad95c324)
Does any one have any suggestion why it happens and what I can to do with it?

**Comment by hsluoyz** [comment]
@Danneborg does other version have this issue? If yes, then it's Java issue. You write Java you know it, Java takes a lot of memory. I don't see abnormal here

If you want to report a bug, say it clearly

**Comment by Danneborg** [comment]
> does other version have this issue
I counted some data from my prod environment, we call enforce around 80-90 times per second, here is the picture of memory consumption. I can't change lib version in prod quickly(
![image](https://github.com/user-attachments/assets/6ecb0c36-4cb0-4552-8fe3-e8c7071e0945)

But I can do it locally. Local test give the same picture, the same jumps when I call enforce. I just want to know, is it okay that jcasbin consumes that much memory for its performance?
![image](https://github.com/user-attachments/assets/b8b06c2b-335b-44ad-ab73-00a3b164a95b)

**Comment by hsluoyz** [comment]
@Danneborg jCasbin uses aviator (https://github.com/killme2008/aviatorscript/blob/master/README-EN.md) for enforcement. You can test that lib directly to see its memory usage. This will help locate the root cause.

**Comment by Danneborg** [comment]
So, I did some performance test for aviator.compile and expression.execute and I can conclude that this two methods consume a lot fo memory, that sad. 
Also I found one suspicious place in jcabin. The digit first looks like the library always iterates the same list of policies without any cache or attempts to reduce number of cycles and inside near digit 2 the code always creates new HashMap that allocates enormous number of object in heap. Do you have any plans to reduce number of cycles or loop peeling?
![image](https://github.com/user-attachments/assets/bb6d52b1-7c47-439a-9962-9e63b2c59160)

**Comment by liewstar** [comment]
> So, I did some performance test for aviator.compile and expression.execute and I can conclude that this two methods consume a lot fo memory, that sad. Also I found one suspicious place in jcabin. The digit first looks like the library always iterates the same list of policies without any cache or attempts to reduce number of cycles and inside near digit 2 the code always creates new HashMap that allocates enormous number of object in heap. Do you have any plans to reduce number of cycles or loop peeling? ![image](https://private-user-images.githubusercontent.com/22558845/352978753-bb6d52b1-7c47-439a-9962-9e63b2c59160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzA0MzEsIm5iZiI6MTcyMjI3MDEzMSwicGF0aCI6Ii8yMjU1ODg0NS8zNTI5Nzg3NTMtYmI2ZDUyYjEtN2M0Ny00MzlhLTk5NjItOWU2M2IyYzU5MTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2MjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MjM4MWE3Y2RhYmI5YjRhNTcxN2UxNjM0MjQzNWExZThkMGJiNmFhODY1MjQzMWU1MjZmY2RmYjFiZDY2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0mOyve2cKzePYMm0y7hQCW4ws08xTAeLkKGBeM6fRaI)

The code you mentioned has been improved in the latest version

your version:1.22.6
``` java
for (int i = 0; i < model.model.get("p").get(pType).policy.size(); i++) {
    List<String> pvals = model.model.get("p").get(pType).policy.get(i);
    // Util.logPrint("Policy Rule: " + pvals);
    // Select the rule based on request size
    Map<String, Object> parameters = new HashMap<>();
    getRTokens(parameters, rvals);
    for (int j = 0; j < model.model.get("p").get(pType).tokens.length; j++) {
        String token = model.model.get("p").get(pType).tokens[j];
        parameters.put(token, pvals.get(j));
    }
    Object result = expression.execute(parameters);
```


latest:
``` java
final List<List<String>> policy = model.model.get("p").get(pType).policy;
final String[] pTokens = model.model.get("p").get(pType).tokens;
final int policyLen = policy.size();
int explainIndex = -1;
if (policyLen != 0 && expString.contains(pType+"_")) {
    policyEffects = new Effect[policyLen];
    matcherResults = new float[policyLen];
    for (int i = 0; i < policy.size(); i++) {
        List<String> pvals = policy.get(i);
        Map<String, Object> parameters = new HashMap<>(rvals.length + pTokens.length);
        getPTokens(parameters, pType, pvals, pTokens);
        getRTokens(parameters, rType, rvals);
        Object result = expression.execute(parameters);

**Comment by Danneborg** [comment]
Thanks for your answers, this tread can be closed
