### ISSUE TITLE
adapter addPolicy should after model.addPolicy ?

### ISSUE THREAD

**Issue by wzhj2326** [casbin/jcasbin#41]
org.casbin.jcasbin.main.InternalEnforcer.java
 //
When the added policy exists, it will cause repeated additions in the storage.
thanks.

**Comment by hsluoyz** [comment]
Hi @wzhj2326 , to keep Casbin an international project, can you modify your text into English please? When it's done, we will answer your question.

**Comment by wzhj2326** [comment]
org.casbin.jcasbin.main.InternalEnforcer.java
 //
When the added policy exists, it will cause repeated additions in the storage.
thanks.

**Comment by fangzhengjin** [comment]
For historical reasons, the current rule deduplication is done by the adapter. You can refer to the method 
[loadPolicy](https://github.com/jcasbin/casbin-spring-boot-starter/blob/master/src/main/java/org/casbin/adapter/JdbcAdapter.java#L99) - [transformToCasbinRule](https://github.com/jcasbin/casbin-spring-boot-starter/blob/master/src/main/java/org/casbin/adapter/CasbinRule.java#L60) custom adapter for processing. We will adjust this feature in a later version.

**Comment by hsluoyz** [comment]
@tldyl please follow how Golang Casbin did: https://github.com/casbin/casbin/pull/490 to fix this issue.
