### ISSUE TITLE
Batch Enforce Limits Arguments

### ISSUE THREAD

**Issue by DonnC** [casbin/jcasbin#414]
I noticed that `batchEnforce(...)` uses the `enforce` method which takes varargs but batchEnforce only passes 3 arguments to the enforce method. https://github.com/casbin/jcasbin/blob/4abeb4a37abae2657a870d8f82a3e48506c24fde/src/main/java/org/casbin/jcasbin/main/Enforcer.java#L626

I have a model as below
```
[request_definition]
r = sub, dom, act, status

[policy_definition]
p = sub, dom, act, status

[policy_effect]
e = some(where (p.eft == allow))

[role_definition]
g = _, _, _

[matchers]
m = g(r.sub, p.sub, r.dom) && r.act == p.act && r.status == p.status || r.sub == "admin"
```

My Policy
```csv
p, viewer, *, read, not_draft_not_final
p, viewer, *, read, final
p, viewer, *, comment, not_draft_not_final

p, auditor, *, read, not_draft
p, auditor, *, read, not_draft_not_final

g, user:1, viewer, document:1
```

When i use batchEnforce im getting the exception message as below
I am passing a list of list of `user:1, document:1, read, not_draft`
```
invalid request size: expected 4, got 3, rvals: [user:1, document:1, read]
```

but it works if i the `.enforce(user:1, document:1, read, not_draft)` directly

**Comment by hsluoyz** [comment]
@DonnC refer to Golang Casbin: https://github.com/casbin/casbin

**Comment by DonnC** [comment]
Thank you, im not familiar that much with go

But from this 
https://github.com/casbin/casbin/blob/master/enforcer.go#L875

It looks like its handled properly in Go since it passes the object array from the arguments,  however in jcasbin, its only taking the first 3 and pass it to the `.enforce(..)` method

**Comment by hsluoyz** [comment]
@DonnC can you make a PR to fix it?

**Comment by DonnC** [comment]
Yes i can, will work on it tomorrow
