### ISSUE TITLE
[bug] migrate OSSRH to Central Portal

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#418]
Right now most of our Java Maven registry pushes in CI failed because OSSRH is deprecated and we should move to the new Central Portal. This is why we has no Maven releases for latest versions and the CI failed: https://github.com/casbin/jcasbin/issues/412

To fix this issue, it seems that we need to modify our CI script to adapt to this new behavior. See docs and articles like:

- https://central.sonatype.org/faq/what-happened-to-issues-sonatype-org/
- https://blog.csdn.net/weixin_45442279/article/details/140469892
- https://blog.csdn.net/GeniusLS/article/details/139903315
- https://blog.allbs.cn/posts/50743/index.html

See our new org in Central Portal: https://central.sonatype.com/namespace/org.casbin

![image](https://github.com/user-attachments/assets/701f1647-24da-44fa-90ca-d953e8f55673)

**Comment by mih-kopylov** [comment]
Waiting for this to be fixed.

It is supposed that the missed releases are published to the Maven Central?

**Comment by hsluoyz** [comment]
v1.63.0 has been released to Maven: https://central.sonatype.com/artifact/org.casbin/jcasbin
