### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 10117 	at org.casbin.jcasbin.main.CoreEnforcer.enforce(

### ISSUE THREAD

**Issue by chinazhaoht** [casbin/jcasbin#420]
When addPolicy is used, the following exception occurs when the enforce method is called:

java.lang.ArrayIndexOutOfBoundsException: 10117
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:638) ~[jcasbin-1.55.0.jar:?]
	
![image](https://github.com/user-attachments/assets/3a82e1a8-1a7d-428d-b57b-32dab6a7a9b1)

These two are not atomic.

**Comment by hsluoyz** [comment]
@chinazhaoht for most cases, this is your own usage issue. Use the online editor to test it first: https://editor.casbin.org/

Or prove it's a Casbin bug (which code line causes which bug because of which reason)
