### ISSUE TITLE
Integrate casbin with jsf

### ISSUE THREAD

**Issue by haramoz** [casbin/jcasbin#45]
Hi, I need to use casbin with jsf for my project. Is there any taglib available for jsf which can be used for role based page display ?

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by fangzhengjin** [comment]
Sorry, we don't have a support plan for jsf yet.

**Comment by hsluoyz** [comment]
Please use SpringBoot.

**Comment by hsluoyz** [comment]
@tldyl can you investigate if we can support JSF?
