### ISSUE TITLE
Delete Permission throw an exception

### ISSUE THREAD

**Issue by ArvinSiChuan** [casbin/jcasbin#46]
when I invocke `enforcer.deletePermission(perm)` while I have no permission assigned to anyone(no this perm record), it throws the following exception:
CasbinAdapterException: Remove filtered policy error, remove 0 rows, expect least 1 rows

I'm using the default model(no conf file).

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by fangzhengjin** [comment]
@ArvinSiChuan ArvinSiChuanHaving a reproducible example would speed up fixing the issue ;)

**Comment by ArvinSiChuan** [comment]
@fangzhengjin I’m using casbin spring boot starter. And when I perform a delete operation like ‘ enforcer.deletePermission(perm)’ without a perm in the casbin rule table it will give me this exception. Looks like it hadn't done anything to deal with this situation (the record not exists) in jdbc adapter.

**Comment by fangzhengjin** [comment]
@ArvinSiChuan Can you provide an engineering example that can reproduce the problem?

**Comment by hsluoyz** [comment]
@ArvinSiChuan show us the code

**Comment by ArvinSiChuan** [comment]
@fangzhengjin
background:
spring boot project, with 2.1.7.RELEASE and casbin spring boot starter the latest

default model, with jdbc adapter 

situation 1
put no data in the table of casbin_rule
excute `enforcer.deletePermission(perm);`

situation 
put some data in the table of casbin_rule：
p ROLE_ADMIN res add
g admin ROLE_ADMIN


excute `enforcer.deletePermission("res","delete");`

**Comment by hsluoyz** [comment]
Please send the issue here instead: https://github.com/jcasbin/casbin-spring-boot-starter

**Comment by ArvinSiChuan** [comment]
refer to https://github.com/jcasbin/casbin-spring-boot-starter/issues/11 now.
