### ISSUE TITLE
jcasbin maven related issue

### ISSUE THREAD

**Issue by haramoz** [casbin/jcasbin#47]
![image](https://user-images.githubusercontent.com/6873268/64875222-ec30f200-d64c-11e9-8c05-7ca1febf522a.png)
Hello I am a jcasbin user. I thank you for the great project. I am using maven. 

- What I noticed is the jar that comes from maven is called **jcasbin-1.2.0**. the current version is 1.4.0 this must be a mistake right?

- also the **exceptions** are not included in the jar

- **FileAdapter** with Inputstream is not included as well in the maven version, which is very useful

**Comment by hsluoyz** [comment]
Please make sure you used this: https://mvnrepository.com/artifact/org.casbin/jcasbin/1.4.0

**Comment by haramoz** [comment]
Yes I used that one! 1.4.0 :)
