### ISSUE TITLE
 Is it good that the code throws java.lang.Error in Java ?

### ISSUE THREAD

**Issue by chinleo** [casbin/jcasbin#5]

**Comment by hsluoyz** [comment]
It's not a good practice. We will fix it these days. You are also welcome to propose PR for us :)

**Comment by hsluoyz** [comment]
Hi @fangzhengjin , can you fix this one?

**Comment by fangzhengjin** [comment]
> Hi @fangzhengjin , can you fix this one?

I will try to fix it, but it may affect some test cases, so the test case must be processed with try catch.

**Comment by hsluoyz** [comment]
Hi @chinleo , this issue has been fixed in: https://github.com/casbin/jcasbin/pull/31
