### ISSUE TITLE
nullPointer at Enforcer 

### ISSUE THREAD

**Issue by amelleHamouch** [casbin/jcasbin#53]
![cas](https://user-images.githubusercontent.com/50912917/74441625-75ed2180-4e70-11ea-9a6b-e8bc2a97f2b7.JPG)
![Capturecas](https://user-images.githubusercontent.com/50912917/74441712-99b06780-4e70-11ea-827a-5a291028e857.JPG)
![null](https://user-images.githubusercontent.com/50912917/74441762-b0ef5500-4e70-11ea-8770-fc655a1a4042.JPG)

It doesn't reach the condition , when I instanciate the Enforcer I immediatly entre the exception , please help

**Comment by hsluoyz** [comment]
Can you debug it and find the crashing line?

**Comment by amelleHamouch** [comment]
Line 69 ,             Enforcer enforcer = new Enforcer(tempConfPath, tempPoliciesPath);
says the enforcer is null

**Comment by hsluoyz** [comment]
I can't squeeze out a bit information time to time like this. Can you provide a full working and runnable example to reproduce?

**Comment by amelleHamouch** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kapiasolutions.karma.filter;

import com.kapiasolutions.karma.util.LogUtil;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.core.CacheControl;
import javax.ws.rs.core.Request;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.ext.Provider;
import org.casbin.jcasbin.main.Enforcer;

/**
 *
 * @author ahamouch
 */
@Provider
public class JCasbinFilter implements ContainerRequestFilter {

    String conf;
    String policies;
    String key = "8y/B?E(H+KbPeShVmYq3t6w9z$C&F)J@";

    @Override
    public void filter(ContainerRequestContext crc) throws IOException {

        try {
            InitialContext initialContext = new InitialContext();
            Context environmentContext = (Context) initialContext.lookup("java:/comp/env");
            configureCasbinFiles(environmentContext);
            UriInfo uriInfo = crc.getUriInfo();
            Request request = crc.getRequest();
            String requestPath = uriInfo.getPath();
            int index = requestPath.lastIndexOf("/");
            String object = requestPath.substring(index);
            String verb = request.getMethod();
            String domain = requestPath.replace(object, "");
            String confContent = decryptFile(key, conf);
            String polContent = decryptFile(key, policies);

            // adresse des fichier temporaires
            String tempConfPath = writeTempFile(confContent, conf);
            String tempPoliciesPath = writeTempFile(polContent, policies);

            //Utilisation de Enforcer de Casbin en lui passant les informations récupéré sur la requête
            Enforcer enforcer = new Enforcer(tempConfPath, tempPoliciesPath);
            //Si False accès non autorisé , requête annulée , envoi de la invalidAccessLevelResponse
            if (enforcer.enforce(object, domain, verb) == false) {
                String msg = String.format("You are not allowed to access this service", requestPath);
                CacheControl cc = new CacheControl();
                cc.setNoStore(true);
                Response invalidAccessLevelResponse = Response.status(Response.Status.FORBIDDEN)
                        .entity(msg)
                        .cacheControl(cc)
                        .build();
                crc.abortWith(invalidAccessLevelResponse);
            }

        } catch (NamingException ex) {
            LogUtil.showLog(ex);
        } catch (Exception ex) {
            Logger.getLogger(JCasbinFilter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //Création de la Réponse en cas d'accès refusé
    //Configuration de Casbin via les variables d'environnement
    private void configureCasbinFiles(Context environmentContext) throws NamingException {

        this.conf = (String) environmentContext.lookup("casbinConf");
        this.policies = (String) environmentContext.lookup("casbinPolicies");

    }

    //Lecture et récupération des données cryptées
    public static byte[] readCasbinFile(String path) throws Exception {

        byte[] encoded;
        encoded = Files.readAllBytes(Paths.get(path));
        return encoded;
    }

    //Génération de la clé à partir du String
    public static SecretKey generateKey(String keyStr) throws NoSuchAlgorithmException {
        KeyGenerator keygen = KeyGenerator.getInstance("AES");
        SecureRandom random = new SecureRandom(keyStr.getBytes());
        keygen.init(random);
        SecretKey secretKey = keygen.generateKey();
        return secretKey;
    }

    //Le fichier est décrypté ici
    public String decryptFile(String key, String path) throws Exception {
        SecretKey secretkey = generateKey(key);
        byte[] cipherText = readCasbinFile(path);
        byte[] IV = new byte[16];
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        SecretKeySpec keySpec = new SecretKeySpec(secretkey.getEncoded(), "AES");
        IvParameterSpec ivSpec = new IvParameterSpec(IV);
        cipher.init(Cipher.DECRYPT_MODE, keySpec, ivSpec);
        byte[] decryptedText = cipher.doFinal(cipherText);
        String decrypt = new String(decryptedText);

        return decrypt;

    }

    //Création du fichier temporaire de config Casbin
    public String writeTempFile(String contentConf, String confFilePath) throws IOException {

        if (confFilePath.contains("model.conf")) {
            String tempPath = confFilePath.replace("model.conf", "tempModel.conf");

            FileWriter writer = new FileWriter(tempPath, false);
            writer.write(contentConf);
            writer.close();
            return tempPath;
        } else {
            String tempPath = confFilePath.replace("karma.policy", "Tempkarma.policy");
            FileWriter writer = new FileWriter(tempPath, false);
            writer.write(contentConf);
            writer.close();
            return tempPath;
        }

    }
}

**Comment by hsluoyz** [comment]
It's better in a GitHub repo, with project files, POM file, etc. So I can run it at once without copy-paste and setup a lot of code.

**Comment by amelleHamouch** [comment]
eh ..I don't have the right to share this code unfortunately ><

**Comment by hsluoyz** [comment]
You should provide a minimized example, only show the bug.

**Comment by dimi-nk** [comment]
I bumped into a similar issue last night. The code that parses the `policy.csv` expects everything to be delimited with `", "` and nothing else. I'll make a PR to make that a bit more lenient.
