### ISSUE TITLE
Whether MySQL 8 is supported？

### ISSUE THREAD

**Issue by laitySunPiaoliang** [casbin/jcasbin#54]
There will be parameters in the URL of MySQL 8. Do you want to confirm whether MySQL 8 is supported? What do you do if you support the parameters in the URL?

![image](https://user-images.githubusercontent.com/13689466/75664540-90ffc400-5cad-11ea-8d1a-31b014e336bf.png)

![image](https://user-images.githubusercontent.com/13689466/75664407-64e44300-5cad-11ea-9426-34e66f13398b.png)

![image](https://user-images.githubusercontent.com/13689466/75664475-7e858a80-5cad-11ea-9223-bda5fe0ea4cf.png)

**Comment by hsluoyz** [comment]
What's your issue? Are you trying to contribute code?

**Comment by laitySunPiaoliang** [comment]
> What's your issue? Are you trying to contribute code?

I'm a user. When I wrote the demo today, I found that this place is'? 'I feel that there is a problem. I want to ask you if there are some parameters used in mysql8. Here is'?' there is a problem

**Comment by hsluoyz** [comment]
I still don't get your question. If you think the current code doesn't support MySQL8, please make a PR to support it.

**Comment by hsluoyz** [comment]
@fangzhengjin

**Comment by fangzhengjin** [comment]
@laitySunPiaoliang If you are a spring / spring boot project, please use [casbin-spring-boot-starter](https://github.com/jcasbin/casbin-spring-boot-starter), if you are an ordinary Java project, please copy [JDBCAdapter.java](https://github.com/jcasbin/jdbc-adapter/blob/master/src/main/java/org/casbin/adapter/JDBCAdapter.java) to the project for modification

**Comment by laitySunPiaoliang** [comment]
@hsluoyz  @fangzhengjin    我应该在 https://github.com/jcasbin/jdbc-adapter  这里提的
