### ISSUE TITLE
MyBatis Adapter wanted

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#56]

**Comment by fanlide** [comment]
I open sourced my own [HutoolDBAdapter etcdWatcher](https://github.com/fanlide/jcasbin-extra)

**Comment by hsluoyz** [comment]
Hi. It should be all English. And there's no MyBatis.

**Comment by fanlide** [comment]
@hsluoyz The first time I wrote it, I also used MyBatis, but I found it more convenient to use this kind of data source in a production environment.

**Comment by codewaiwai** [comment]
Hi~I want to finish this task. And I know that the adapters code for Casbin(golang) is separated from Casbin. Is it same with JCasbin? Should I make a PR in this repo?

**Comment by hsluoyz** [comment]
Fork this repo: https://github.com/jcasbin/mybatis-adapter and make PR.

**Comment by hsluoyz** [comment]
@tldyl is working on it: https://github.com/jcasbin/mybatis-adapter
