### ISSUE TITLE
Integration with Apache Shiro and Spring Security

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#57]
In Java world, Apache Shiro and Spring Security are very popular security frameworks. We need to find ways to wrap jCasbin into a middleware of the above both, so Shiro and Spring users can use jCasbin without much migration efforts.

**Comment by fanlide** [comment]
I have a project [shiro-jrc-starter](https://github.com/fanlide/shiro-jrc-starter) that is using Apache Shiro integrated jcasbin, jwt, redis, but I haven't written instructions yet. I hope it can be of some use to you.

The project is not in English for the time being. If it is useful, I will change it later.

**Comment by fanlide** [comment]
I sorted out a separate Shiro integrates Casbin starter [shiro-jcasbin-spring-boot-starter](https://github.com/fanlide/shiro-jcasbin-spring-boot-starter).

**Comment by hsluoyz** [comment]
@fanlide added to: https://casbin.org/docs/en/middlewares

**Comment by fanlide** [comment]
My pleasure
