### ISSUE TITLE
[Need help] How to secure a Rest api?

### ISSUE THREAD

**Issue by Steinliiippp** [casbin/jcasbin#6]
I want to secure a REST-Api with jcasbin. But i dont get the right place to start.

Is this the right practice?

URL: ``/api/v1/user/10``

```java
public Result showUser(int id){
       User user = UserService.getUser(id);
       if(isAllowed(session.get(userID), 10, GET)){
              return success;
       }else{
              return error;
       }
}

private boolean isAllowed(String userId, String data, String action){
       enforcer.addPolicy(userId, data, action);
       return enforcer.enforce(userId, data, action);
}
```

config-file: 

```ini
[request_definition]
r = acc, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.acc== p.acc && r.obj == p.obj && r.act == p.act
```

I'm asking this because of:

I can not set policys in advance, because i dont know all users
I can not set policiys in advance, because i dont know the id of the resource
I can not set policiys in advance, because i dont know the Action of the request
Maybe im stupid but i dont get it ................ in german it is called "auf dem Schlauch stehen" (stand on the hose)

Could you show me a short REST-Example in Java where i could start? Is my example useable? I dont think so, because of the ``enforcer.addPolicy(userId, data, action);`` call ....

**Comment by hsluoyz** [comment]
Hi @Steinliiippp , sorry to respond so late, you could first go through our tutorials a bit here: https://casbin.org/docs/en/tutorials, especially the HTTP & RESTful tutorial. Then you should know how to define your ``sub, obj, act``.

**Comment by hsluoyz** [comment]
Closed as stale.
