### ISSUE TITLE
Java's SyncedEnforcer lacks some methods compared to Golang

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#60]
Java: https://github.com/casbin/jcasbin/blob/master/src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java

Golang: https://github.com/casbin/casbin/blob/master/enforcer_synced.go

Functions like `LoadPolicy()` are missing. Can anyone add the missing functions?

**Comment by DivyPatel9881** [comment]
I will add the missing functions.

**Comment by doctormacky** [comment]
Any ETA for this issue ?

**Comment by hsluoyz** [comment]
I think we can fix this in 3 days? @nodece @fangzhengjin @DivyPatel9881

**Comment by DivyPatel9881** [comment]
Yeah, I just have to setup my Java working env for this, as it contains many 3-party dependencies, can I ask, which platform or IDE should I use for the development of jcasbin

**Comment by DivyPatel9881** [comment]
Yeah it will be done in 3days

**Comment by hsluoyz** [comment]
IntelliJ IDEA
