### ISSUE TITLE
DynamoDB adapter or any other serverless DB adapter wanted for jCasbin

### ISSUE THREAD

**Issue by alikhan866** [casbin/jcasbin#62]
I'm using Casbin on the backend which uses java.. so i need to store my policies in a `Serverless DB` so that i dont have to worry about scalability/maintainence using `Casbin  DB adapter`

**Comment by hsluoyz** [comment]
@alikhan866 can you develop one?

**Comment by alikhan866** [comment]
@hsluoyz I don't think i can .. else i would have implemented it and created a PR ... would really appreciate any alternative suggestions on how to use a serverless DB in my java backend to store and retrieve policies using Casbin if there are any :)

**Comment by hsluoyz** [comment]
Can anyone do this? @nodece

**Comment by nodece** [comment]
Sorry, I don't have serverless DB experience.

**Comment by alikhan866** [comment]
@hsluoyz  Is anyone working on this ? If yes can you please give me an ETA so i can proceed with my project accordingly :)

**Comment by hsluoyz** [comment]
I think this work is simple. We already have Golang's DynamoDB adapter: https://github.com/HOOQTV/dynacasbin and Java's other adapters like:

https://github.com/jcasbin/jdbc-adapter
https://github.com/fanlide/jcasbin-extra

Mixing them together will ease the development of the Java's DynamoDB adapter.

**Comment by kingiw** [comment]
Maybe I can have a try on that.

**Comment by nodece** [comment]
@hsluoyz Could your create a DynamoDB adapter repository for @kingiw ?

**Comment by hsluoyz** [comment]
@nodece created: https://github.com/jcasbin/dynamodb-adapter

**Comment by hsluoyz** [comment]
@kingiw the adapter is already available in Maven: https://mvnrepository.com/artifact/org.casbin/dynamodb-adapter

Can you update the README's badges and install command (https://github.com/jcasbin/dynamodb-adapter)? See jCasbin as an example: https://github.com/casbin/jcasbin

![image](https://user-images.githubusercontent.com/3787410/82860583-b1f25100-9f4c-11ea-993a-4ebfcb5e1a60.png)

![image](https://user-images.githubusercontent.com/3787410/82860605-bc144f80-9f4c-11ea-9cea-2d606faea995.png)

**Comment by kingiw** [comment]
@hsluoyz See the latest [PR](https://github.com/jcasbin/dynamodb-adapter/pulls?q=is%3Aopen+is%3Apr).

**Comment by hsluoyz** [comment]
@alikhan866 it's finished: https://github.com/jcasbin/dynamodb-adapter
