### ISSUE TITLE
Potential partial/complete dataloss in savePolicy.

### ISSUE THREAD

**Issue by bpatters** [casbin/jcasbin#64]
Failure in the savePolicy function can lead to a complete loss of all data because savePolicy doesn't use transactions  AND:
1. First drops the table
2. Recreates the table.
3. Executes a batch of inserts to save the policy.

If 1 succeed and a failure occurs anytime after it can lead to a partial or complete data loss.

It'd be much safer if it:
1. Started a transaction
2. Deleted everything in the table (not drop table, mysql doesn't support DML transactions)
3. Inserted the new policy.
4. Committed the transaction.

I actually don't see any usage of transactions in this Adapter, which is worrisome, but maybe I'm missing something?

**Comment by bpatters** [comment]
whoops wrong repo.

**Comment by nodece** [comment]
Thanks @bpatters for your report. 

Data is very valuable, We can not allow this to happen!

I will take up it.

**Comment by hsluoyz** [comment]
Let's discuss in: https://github.com/jcasbin/jdbc-adapter/issues/14
