### ISSUE TITLE
Implement the loadFilteredPolicy() function

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#66]
It is not implemented yet:

https://github.com/casbin/jcasbin/blob/78ea156f09ae4a75579ad563866be66d49887c8e/src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java#L207-L214

I want to fix this because we received a PR: https://github.com/casbin/jcasbin/pull/65

**Comment by hsluoyz** [comment]
@nodece @GopherJ @xcaptain @fangzhengjin

**Comment by DivyPatel9881** [comment]
Can I take this issue?

**Comment by nodece** [comment]
@DivyPatel9881  Okey.

**Comment by DivyPatel9881** [comment]
This will require the implementation of a Filtered adapter interface.

**Comment by hsluoyz** [comment]
@DivyPatel9881 do you have time to solve this one?

If Divy doesn't have time, can anyone take this? @nodece @GopherJ @kingiw @dovics @hackerchai I don't want this PR: https://github.com/casbin/jcasbin/pull/65 to be merged.

**Comment by hsluoyz** [comment]
@tldyl can you take this issue?

**Comment by hsluoyz** [comment]
Implemented in: https://github.com/casbin/jcasbin/pull/77
