### ISSUE TITLE
How to check whether the adapter can be updated successfully?

### ISSUE THREAD

**Issue by nodece** [casbin/jcasbin#67]
I find that each methods of `adapter` returns `void` .

In Casbin, How to check whether the adapter can be updated successfully?

If no has ACK,  will cause data loss.

**Comment by hsluoyz** [comment]
Golang return errors, so I think Java will throw exceptions?

**Comment by nodece** [comment]
The correct signature should be like this:
```
 void loadPolicy(Model model) throws Exception;
```

**Comment by hsluoyz** [comment]
OK. Can anyone fix it?

**Comment by nodece** [comment]
I fix it as soon as possible and it as breaking change.

**Comment by nodece** [comment]
Sorry I provide a wrong issue.  

`adapter` can `throws` any exception,  but I think of explicit declaration is good habit.
