### ISSUE TITLE
NullPointer appears in hasRoleForUser

### ISSUE THREAD

**Issue by fanlide** [casbin/jcasbin#69]
![image](https://user-images.githubusercontent.com/20534139/81139031-dd5dcd80-8f96-11ea-8e53-4ffd9d8afad5.png)

This should be a design issue with getRolesForUser.
When user does not assign role, it should return empty list instead of null.
Similarly, the same should be true for getUsersForRole, getRolesForUserInDomain, etc.

**Comment by hsluoyz** [comment]
@fanlide can you make a PR to fix it?

**Comment by fanlide** [comment]
Very happy to
