### ISSUE TITLE
API enhancement requirement: batch object API for permission validation

### ISSUE THREAD

**Issue by The-Mountain** [casbin/jcasbin#71]
HI there, 
I have a requirement in our business to validate the permission for inputed multiple objects and filter the objects which current user don't have permission to access, it seems that current verion API can't support it, please assess if can be added in your furture version, if this could not be in your scope, batch api for permission validation is also ok,that would be highly appreciate if scheduled release date could be provided, thanks!

**Comment by nodece** [comment]
Could you try the `enforcer.getImplicitPermissionsForUser`?

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by hsluoyz** [comment]
Closed as resolved.
