### ISSUE TITLE
New API requirement: get subject's available actions list for inputed object

### ISSUE THREAD

**Issue by The-Mountain** [casbin/jcasbin#72]
HI there,
I have a requirement in our business to get user's permission list for specified object, it seems that current verion API can't support it, please assess if could be added in your furture version, that would be highly appreciate if scheduled release date could be provided, thanks!

**Comment by hsluoyz** [comment]
@The-Mountain what's this difference with https://github.com/casbin/jcasbin/issues/71?

**Comment by The-Mountain** [comment]
@hsluoyz the difference is #71 is need framework to filter the unauthorized objects, e.g. 10 request/objects are inputed to this API, if currenct user don't have permisson to access two of them,  then API should filter theese two requests/objects, and return other 8 requests or objects with valid permission, #72 is need framwork to get valid actions on inputed object for current user, e.g. we totally define 4 actions(read, create, modify, delete) for one model, and if current user only have read and modifiy permission for the object inputed, then this API should return a list with read and modifiy

**Comment by hsluoyz** [comment]
They seem the same to me. Both are "filtering".

**Comment by hsluoyz** [comment]
We should add the filtering functionality to Casbin. Any idea to how to implement it? @nodece @GopherJ @DivyPatel9881 @kingiw

**Comment by The-Mountain** [comment]
> They seem the same to me. Both are "filtering".

ok, I got your point, from internal logic implementation they are both filtering,  but from API perspective，for more convenience to invoke these APIs,  the input and output of these two APIs should be different

**Comment by nodece** [comment]
Could you try the `enforcer.getFilteredPolicy` and `enforcer.getFilteredGroupingPolicy`?

**Comment by kingiw** [comment]
@hsluoyz Can we add this api (and other similar apis like this one) to other version of Casbin?
