### ISSUE TITLE
The benchmark for jcasbin

### ISSUE THREAD

**Issue by The-Mountain** [casbin/jcasbin#73]
Hi there, 
As we may have millions of policies in our business, not sure the currect framework could support such so large policies? if it will cause the OOM issue? or other perfromance issues? is there a benchmark for jcasbin? thanks.

**Comment by hsluoyz** [comment]
Can anyone port Golang's benchmark test to Java? https://casbin.org/docs/en/benchmark

@nodece @GopherJ @DivyPatel9881 @kingiw @hackerchai @dovics

**Comment by hsluoyz** [comment]
@happybyr Can you help solve it?

**Comment by hsluoyz** [comment]
@The-Mountain it has been fixed in: https://github.com/casbin/jcasbin/pull/74

**Comment by The-Mountain** [comment]
> @The-Mountain it has been fixed in: #74

@hsluoyz thanks for the support!
