### ISSUE TITLE
Use semantic-release to automatically release jCasbin versions

### ISSUE THREAD

**Issue by hsluoyz** [casbin/jcasbin#76]
We already used semantic-release in Go and Nodejs, see Node-Casbin: https://github.com/casbin/node-casbin/pull/153#issuecomment-625775348

![image](https://user-images.githubusercontent.com/3787410/83984606-7aca6980-a968-11ea-8eef-49f5fbd45008.png)

I think we should also integrate it into Java. It will auto-release to GitHub Releases and Maven via plugin: https://github.com/conveyal/maven-semantic-release

Can anyone work on it?

**Comment by hsluoyz** [comment]
Can anyone work on it? @tldyl

**Comment by hsluoyz** [comment]
@tldyl any update?

**Comment by hsluoyz** [comment]
@tldyl

**Comment by hsluoyz** [comment]
@shy1st we can work on this issue as next step.

**Comment by hsluoyz** [comment]
@shy1st well done! We finally got this issue resolved.

So here's how to deploy a new jCasbin version:

```
mvn release:prepare
<input your new version like 1.2.3>
mvn release:perform
```

**Comment by shy1st** [comment]
I think this issue have not finished.In fact,a file named ".travis.yml" which I modified have not commit.I plan when I success to release jcasbin 1.6.3 fot the maven reponsitory and github release, then I create a pull request to commit the ".travis.yml".After that I think we can close this issue.What do you think about it? @hsluoyz

**Comment by hsluoyz** [comment]
Sounds reasonable. Go ahead!
