### ISSUE TITLE
Performance problem of CoreEnforcer.enforce

### ISSUE THREAD

**Issue by bgranvea** [casbin/jcasbin#78]
In my use case of jcasbin, I have many calls of CoreEnforcer.enforce and this becomes a performance bottleneck. The root cause seems to be in these lines:

```java
        AviatorEvaluatorInstance eval = AviatorEvaluator.newInstance();
[...]
        String expString = model.model.get("m").get("m").value;
        Expression expression = eval.compile(expString);
```

The compiled expression is very likely to be the same each time and it is parsed and recompiled each time. Shouldn't we instanciate `AviatorEvaluatorInstance` only once and use `eval.compile(expString, true)` to get a cached expression?

**Comment by hsluoyz** [comment]
Hi @bgranvea this is a known issue. Actually there's a PR about it: https://github.com/casbin/jcasbin/pull/44 but this PR is rejected because of some multi-threading handling issue.

Can you make a PR (based on that PR if you wish, or not) to solve it?

**Comment by bgranvea** [comment]
ok thanks I will try to do a PR.

**Comment by bgranvea** [comment]
What is tricky is to manage when to reset AviatorEvaluatorInstance because of a change in this list of functions:

```
CoreEnforcer.enforce:

       Map<String, AviatorFunction> functions = new HashMap<>();
        for (Map.Entry<String, AviatorFunction> entry : fm.fm.entrySet()) {
            String key = entry.getKey();
            AviatorFunction function = entry.getValue();

            functions.put(key, function);
        }
        if (model.model.containsKey("g")) {
            for (Map.Entry<String, Assertion> entry : model.model.get("g").entrySet()) {
                String key = entry.getKey();
                Assertion ast = entry.getValue();

                RoleManager rm = ast.rm;
                functions.put(key, BuiltInFunctions.generateGFunction(key, rm));
            }
        }
```

First approach is to check if this list is the same as before (it must then be ordered and we can just compare references to AviatorFunction and Assertion), but we still have to build the list each time and I am not sure how large it can be.

Another approach is to check all places where FunctionMap and Model data can be modified but I will have to add a 'version' field that is incremented each time there is a change, for example in Model.addDef, Policy.addPolicy...
 
What do you think?

**Comment by hsluoyz** [comment]
> Another approach is to check all places where FunctionMap and Model data can be modified but I will have to add a 'version' field that is incremented each time there is a change, for example in Model.addDef, Policy.addPolicy...

This way is better in performance. But why version is needed? You can set the AviatorEvaluatorInstance to null. And for next time if it is found to be null, then a new instance will be created.

**Comment by bgranvea** [comment]
yes that's the solution in PR #44 but I was not very happy with the shared singleton. I wanted to keep a AviatorEvaluatorInstance field inside CoreEnforcer but this implies that Model and FunctionMap have a reference to CoreEnforcer.

If I understand correctly, you are more on the singleton solution + ThreadLocal?

**Comment by hsluoyz** [comment]
What do you mean by **singleton**? I assumed `AviatorEvaluatorInstance` would be a member of an enforcer instance. Are we on the same page?

**Comment by bgranvea** [comment]
ok I will do a first PR so that we can talk more concretely.

**Comment by bgranvea** [comment]
Thanks for merging my PR. Any idea of a date for the next release?
