### ISSUE TITLE
"Could not find function named 'eval'" when trying with ABAC example

### ISSUE THREAD

**Issue by JavaMiner** [casbin/jcasbin#84]
Running example from the chapter [Scaling the model for complex and large number of ABAC rules](https://casbin.org/docs/en/abac#scaling-the-model-for-complex-and-large-number-of-abac-rules)
end-up with exception:
`com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find function named 'eval'`

Could you please advise how to enable the eval() method in jCasbin?

**Comment by hsluoyz** [comment]
@JavaMiner the eval() feature is still not added to jCasbin.

@tldyl can you add the scaling ABAC feature?
