### ISSUE TITLE
Missing built-in function `keyMatch3` and `keyMatch4`

### ISSUE THREAD

**Issue by quytm-teko** [casbin/jcasbin#89]
https://github.com/casbin/jcasbin/blob/c8f092320a67e376bbb906a1741aa01335583f13/src/main/java/org/casbin/jcasbin/model/FunctionMap.java#L47

`FunctionMap` is out-of-date, please add missing built-in functions `keyMatch3` and `keyMatch4`.

Thanks! ^^

**Comment by hsluoyz** [comment]
@tldyl please take this issue to work on.

**Comment by hsluoyz** [comment]
@tldyl PR merged, can you make a new release?
