### ISSUE TITLE
How to Define ABAC roles 

### ISSUE THREAD

**Issue by M-Razavi** [casbin/jcasbin#9]
Hi 
I want to use ABAC authorization for one of my application but I don't how to define roles and policies.
Let me describe the scenario:
1-**Subject:** There roles(Operator, Manager, Reviewer) and each User has a Branch. 
2- **Resource:** There are several Object (Order, Document,..), and each Object has a Branch.
3- **Actions:** There are some actions such as Create, Edit, View, Confirm, Reject.

Some policies:
1- All User can View to objects if  object.branch in user.branch 
2- All user can do actions on objects during wroking time (8:30 - 17:00)
3- Manager can View to objects whenever they want.
4- User with name X has Branch A,B.
5- Manager can do Confirm and Reject.
6- Operator can do View and Create
7- Reviewer can only view objects if object. status= confirmed.

Would you please help me how to define these scenario?

![roles](https://user-images.githubusercontent.com/6397404/51528639-5988dc00-1e4c-11e9-9586-8038fe85a55f.png)

**Comment by hsluoyz** [comment]
Hi @M-Razavi ,

> 1- All User can View to objects if object.branch in user.branch

```ini
r.act == "View" && r.obj.branch in r.sub.branch
```

> 2- All user can do actions on objects during wroking time (8:30 - 17:00)

```ini
isWorkingTime()
```

> 3- Manager can View to objects whenever they want.

```ini
g(r.sub, "Manager") && r.act == "View"
```

> 4- User with name X has Branch A,B.

Don't know what it means.

> 5- Manager can do Confirm and Reject.

```ini
g(r.sub, "Manager") && (r.act == "Confirm" || r.act == "Reject")
```

> 6- Operator can do View and Create

Similar as above.

> 7- Reviewer can only view objects if object. status= confirmed.

```ini
g(r.sub, "Reviewer") && r.obj.status== "confirmed"
```

Finally, you can connect the above assertions with ``||`` and use it in a matcher.

**Comment by M-Razavi** [comment]
4- A user with user name 'XYZ'  has 2 branch ( xyz.branches = [Location1,Location2] )

Is it possible to have multiple roles for a user?

How can I define time sheet for some of the users in policy?

**Comment by hsluoyz** [comment]
> 4- A user with user name 'XYZ' has 2 branch ( xyz.branches = [Location1,Location2] )

I mean it's not access control, there's no asking for permission. That user of course can have 2 branches or more. It all depends on you. What do you expect Casbin to do for this?

> Is it possible to have multiple roles for a user?

Yes, of course. That's what RBAC does.

> How can I define time sheet for some of the users in policy?

Casbin doesn't have a concept called time sheet or any other time-related built-in functionality. You have to define it yourself as a custom function. Any field in Casbin is string, so how to use it depends on you.

**Comment by M-Razavi** [comment]
I defined the matcher as below but got an error

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.act == "View" && r.obj.branch in r.sub.branch || g(r.sub, "Manager") && r.act == "View" ||  isValidTimeForUser(r.sub) || g(r.sub, "Manager") && (r.act == "Confirm" || r.act == "Reject")  || g(r.sub, "Operator") && (r.act == "Create" || r.act == "Edit") || g(r.sub, "Reviewer") && r.obj.status== "confirmed"
```

> m.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error:Unexpect token 'in' at 32, current token: [type='variable',lexeme='in',index=32]. Parsing expression: `r_act == "View" && r_obj.branch in^^`

**Comment by hsluoyz** [comment]
``in`` operator is only supported by Golang' Casbin, see last paragraph of this: https://github.com/casbin/casbin#how-it-works. This is because jCasbin's evaluator: https://github.com/killme2008/aviator doesn't support ``in``. You have to define a custom function as a workaround:

```ini
isIn(r.obj.branch, r.sub.branch)
```

**Comment by LimitlessKshitij** [comment]
Hi @M-Razavi I am new to casbin, I want to use ABAC in conjugation with RBAC and ACL, I have created custom aviation functions and used them in matchers as well but enforcing the rule is kind a little tricky, If possible can you provide some workable code for referencing. For example,the use case is: I want to provide limited access to set  of people and to roles if they are calling within the particular time period. Your queries are really helpful in getting the incite of how ABAC works. Thanks in advance.
