### ISSUE TITLE
How does jcasbin connect to the database？

### ISSUE THREAD

**Issue by liergou99** [casbin/jcasbin#91]
How jcasbin connects to the database, for example: mysql, pg. Can jcasbin use an external authority table like SpringSecurity?

**Comment by hsluoyz** [comment]
@liergou99 jCasbin supports a lot of DBs, see the adapters under the Java tab: https://casbin.org/docs/en/adapters

**Comment by liergou99** [comment]
It seems that Casbin's adapter cannot use external tables.

**Comment by liergou99** [comment]
It seems that Casbin's adapter cannot use external tables.

**Comment by hsluoyz** [comment]
What do you mean by "external tables"?

**Comment by liergou99** [comment]
When the application system uses casbin for permission verification, the system will have its own user system instead of using the adapter’s "casbin_rule" table

**Comment by liergou99** [comment]
When the application system uses casbin for permission verification, the system will have its own user system instead of using the adapter’s "casbin_rule" table

**Comment by liergou99** [comment]
The application system generally has its own user table, such as users, roles, etc.

**Comment by hsluoyz** [comment]
Most adapters allow you to specify a DB name in args, so you can point it to an existing DB. By default it will save/load a table named "casbin_rule".
